// Table des infractions — codes de la feuille de match SIHF, sanctions
// possibles, critere de jugement et renvoi vers la fiche de poche.
// Genere depuis penalties_content.py — ne pas editer a la main.
//
// `crit` est un fragment statique produit ici, jamais une saisie utilisateur.
// `fiche` est resolu a la generation : il suit les renumerotations du paquet.

export type Family = 'charges' | 'coups' | 'crosse' | 'destructives'
  | 'officiels' | 'types' | 'autres'

export interface Penalty {
  /** Code a inscrire sur la feuille de match. */
  code: string
  fam: Family
  fr: string
  en: string
  /** Sanctions possibles, de la plus legere a la plus lourde. */
  sanctions: string[]
  crit: string
  /** Numero de la fiche de poche qui detaille la faute. */
  fiche: number
  ficheTitre: string
  search: string
}

export const SANCTIONS: { key: string; label: string; tone: string }[] = [
  { key: "2'", label: "Pénalité mineure 2'", tone: "s-min" },
  { key: "PBM", label: "Pénalité de banc mineure 2'", tone: "s-bench" },
  { key: "2+2", label: "Double mineure 2'+2'", tone: "s-dbl" },
  { key: "5'", label: "Pénalité majeure 5'", tone: "s-maj" },
  { key: "5+PMM", label: "Majeure 5' + méconduite de match", tone: "s-majpmm" },
  { key: "10'", label: "Méconduite 10'", tone: "s-misc" },
  { key: "PMM", label: "Méconduite de match", tone: "s-pmm" },
  { key: "TIR", label: "Tir de pénalité", tone: "s-ps" },
  { key: "BUT", label: "But accordé", tone: "s-goal" },
  { key: "selon", label: "Selon le livre de règles", tone: "s-rule" },
  { key: "---", label: "Arrêt de jeu, sans pénalité", tone: "s-none" },
]

export const FAMILIES: { key: Family; label: string; short: string }[] = [
  { key: 'charges', label: "Charges", short: "Charges" },
  { key: 'coups', label: "Coups", short: "Coups" },
  { key: 'crosse', label: "Fautes de crosse", short: "Crosse" },
  { key: 'destructives', label: "Fautes destructives", short: "Destructives" },
  { key: 'officiels', label: "Officiels & antisportif", short: "Officiels" },
  { key: 'types', label: "Types de sanction", short: "Types" },
  { key: 'autres', label: "Autres fautes", short: "Autres" },
]

export const PENALTIES: Penalty[] = [
  {
    code: "8",
    fam: 'autres',
    fr: "Joueur blessé — obligations",
    en: "Injured player",
    sanctions: ["2'", "PBM"],
    crit: "Feindre une blessure ou refuser de se relever → <b>2'</b>. Sortie du blessé ailleurs qu'au banc → <b>PBM</b>. Sang visible : renvoi de la glace au prochain arrêt.",
    fiche: 55,
    ficheTitre: "Blessure & sang (8)",
    search: "8 joueur blesse — obligations injured player feindre une blessure ou refuser de se relever → 2'. sortie du blesse ailleurs qu'au banc → pbm. sang visible : renvoi de la glace au prochain arret. 2' pbm",
  },
  {
    code: "10",
    fam: 'crosse',
    fr: "Crosse non conforme · crosse brisée",
    en: "Illegal / broken stick",
    sanctions: ["2'", "PBM", "10'"],
    crit: "Jouer avec une crosse <b>brisée</b> ou avec <b>deux crosses</b> → 2'. Briser sa crosse ou refuser de la remettre pour mesure → 10'. Demande de mesure <b>non fondée</b> → PBM.",
    fiche: 53,
    ficheTitre: "Canne & crosse cassée",
    search: "10 crosse non conforme · crosse brisee illegal / broken stick jouer avec une crosse brisee ou avec deux crosses → 2'. briser sa crosse ou refuser de la remettre pour mesure → 10'. demande de mesure non fondee → pbm. 2' pbm 10'",
  },
  {
    code: "21",
    fam: 'autres',
    fr: "Action dangereuse non couverte",
    en: "Dangerous action",
    sanctions: ["5+PMM"],
    crit: "Le code de secours pour un geste dangereux qu'aucune autre règle ne couvre. <b>Une seule sanction possible.</b>",
    fiche: 21,
    ficheTitre: "Majeures 5'",
    search: "21 action dangereuse non couverte dangerous action le code de secours pour un geste dangereux qu'aucune autre regle ne couvre. une seule sanction possible. 5+pmm",
  },
  {
    code: "23",
    fam: 'types',
    fr: "Méconduite de match",
    en: "Game misconduct",
    sanctions: ["PMM"],
    crit: "Expulsion, <b>20' inscrites</b>, <b>rapport obligatoire</b>. Automatique sur 2e majeure ou 2e méconduite du match, et avec <b>toute majeure en espoirs</b>.",
    fiche: 23,
    ficheTitre: "Méconduite de match (PMM)",
    search: "23 meconduite de match game misconduct expulsion, 20' inscrites, rapport obligatoire. automatique sur 2e majeure ou 2e meconduite du match, et avec toute majeure en espoirs. pmm",
  },
  {
    code: "24",
    fam: 'types',
    fr: "Tir de pénalité",
    en: "Penalty shot",
    sanctions: ["TIR"],
    crit: "Les <b>4 conditions</b> : zone neutre ou d'attaque · faute <b>par derrière</b> · possession et contrôle du puck · <b>aucun adversaire</b> entre le joueur et le gardien.",
    fiche: 24,
    ficheTitre: "Tir de pénalité (24)",
    search: "24 tir de penalite penalty shot les 4 conditions : zone neutre ou d'attaque · faute par derriere · possession et controle du puck · aucun adversaire entre le joueur et le gardien. tir",
  },
  {
    code: "25",
    fam: 'types',
    fr: "But accordé",
    en: "Awarded goal",
    sanctions: ["BUT"],
    crit: "Toutes les conditions du tir de pénalité réunies alors que le <b>gardien n'est plus en jeu</b>. Gardien présent, deux cas quand même : masque <b>retiré volontairement</b> ou <b>but déplacé</b> lors d'une échappée.",
    fiche: 25,
    ficheTitre: "But accordé (25)",
    search: "25 but accorde awarded goal toutes les conditions du tir de penalite reunies alors que le gardien n'est plus en jeu. gardien present, deux cas quand meme : masque retire volontairement ou but deplace lors d'une echappee. but",
  },
  {
    code: "27",
    fam: 'autres',
    fr: "Pénalités du gardien",
    en: "Goalkeeper penalties",
    sanctions: ["2'", "5+PMM"],
    crit: "Le gardien <b>ne purge jamais</b> : un joueur désigné va au banc. Quitter sa zone lors d'une altercation, jouer au-delà de la médiane, lancer le puck vers le but adverse → 2'. Sa <b>2e majeure</b> du match → PMM automatique.",
    fiche: 14,
    ficheTitre: "Types de pénalités",
    search: "27 penalites du gardien goalkeeper penalties le gardien ne purge jamais : un joueur designe va au banc. quitter sa zone lors d'une altercation, jouer au-dela de la mediane, lancer le puck vers le but adverse → 2'. sa 2e majeure du match → pmm automatique. 2' 5+pmm",
  },
  {
    code: "38",
    fam: 'autres',
    fr: "Coach's Challenge",
    en: "Coach's Challenge",
    sanctions: ["2+2"],
    crit: "<b>Non appliqué en SEAF</b> — ni Coach's Challenge ni Video Review en sport espoir, amateur et féminin.",
    fiche: 16,
    ficheTitre: "Pénalités concomitantes",
    search: "38 coach's challenge coach's challenge non applique en seaf — ni coach's challenge ni video review en sport espoir, amateur et feminin. 2+2",
  },
  {
    code: "39",
    fam: 'officiels',
    fr: "Incorrection envers les officiels",
    en: "Abuse of officials",
    sanctions: ["2'", "PBM", "10'", "PMM"],
    crit: "<b>Une question n'est pas une contestation.</b> Joueur : 2' → 10' → PMM. Staff : avertissement formel → PBM → PMM. Frapper bandes ou vitres en protestation compte.",
    fiche: 57,
    ficheTitre: "Escalade & officiels",
    search: "39 incorrection envers les officiels abuse of officials une question n'est pas une contestation. joueur : 2' → 10' → pmm. staff : avertissement formel → pbm → pmm. frapper bandes ou vitres en protestation compte. 2' pbm 10' pmm",
  },
  {
    code: "40",
    fam: 'officiels',
    fr: "Violence physique sur un officiel",
    en: "Physical abuse of officials",
    sanctions: ["PMM"],
    crit: "Tout contact physique <b>volontaire</b> envers un officiel. <b>Une seule sanction possible</b>, et un rapport précis.",
    fiche: 57,
    ficheTitre: "Escalade & officiels",
    search: "40 violence physique sur un officiel physical abuse of officials tout contact physique volontaire envers un officiel. une seule sanction possible, et un rapport precis. pmm",
  },
  {
    code: "41",
    fam: 'charges',
    fr: "Charge contre la bande",
    en: "Boarding",
    sanctions: ["2'", "5'", "5+PMM"],
    crit: "<b>Distance</b> à la bande et <b>vulnérabilité</b> du joueur checké ; pouvait-on <b>éviter ou réduire</b> la charge ? La bande augmente fortement le risque.",
    fiche: 26,
    ficheTitre: "Charges — le critère",
    search: "41 charge contre la bande boarding distance a la bande et vulnerabilite du joueur checke ; pouvait-on eviter ou reduire la charge ? la bande augmente fortement le risque. 2' 5' 5+pmm",
  },
  {
    code: "42",
    fam: 'charges',
    fr: "Charge incorrecte",
    en: "Charging",
    sanctions: ["2'", "5'", "5+PMM"],
    crit: "<b>Distance et vitesse</b> prises avant le contact ; joueur qui <b>saute</b> ou se projette ; force excessive ou contact <b>évitable</b>.",
    fiche: 26,
    ficheTitre: "Charges — le critère",
    search: "42 charge incorrecte charging distance et vitesse prises avant le contact ; joueur qui saute ou se projette ; force excessive ou contact evitable. 2' 5' 5+pmm",
  },
  {
    code: "43",
    fam: 'charges',
    fr: "Charge par derrière",
    en: "Checking from behind",
    sanctions: ["5+PMM", "TIR"],
    crit: "Il <b>ne voit pas venir</b> et ne peut pas se protéger ; contact principal <b>dans le dos</b>. S'il se <b>tourne au dernier moment</b>, ce n'est pas 43. <b>Toujours 5' + PMM.</b>",
    fiche: 26,
    ficheTitre: "Charges — le critère",
    search: "43 charge par derriere checking from behind il ne voit pas venir et ne peut pas se proteger ; contact principal dans le dos. s'il se tourne au dernier moment, ce n'est pas 43. toujours 5' + pmm. 5+pmm tir",
  },
  {
    code: "44",
    fam: 'coups',
    fr: "Coupage (charge contre le genou)",
    en: "Clipping",
    sanctions: ["2'", "5+PMM"],
    crit: "<b>Corps abaissé</b> volontairement pour charger <b>au niveau ou sous les genoux</b>. À distinguer du coup de genou 50.",
    fiche: 27,
    ficheTitre: "Coups — le critère",
    search: "44 coupage (charge contre le genou) clipping corps abaisse volontairement pour charger au niveau ou sous les genoux. a distinguer du coup de genou 50. 2' 5+pmm",
  },
  {
    code: "45",
    fam: 'coups',
    fr: "Coup de coude",
    en: "Elbowing",
    sanctions: ["2'", "5'", "5+PMM"],
    crit: "Coude <b>sorti activement</b> vers l'adversaire, et non laissé en position <b>naturelle</b>. Ce n'est pas le contact, c'est l'usage.",
    fiche: 27,
    ficheTitre: "Coups — le critère",
    search: "45 coup de coude elbowing coude sorti activement vers l'adversaire, et non laisse en position naturelle. ce n'est pas le contact, c'est l'usage. 2' 5' 5+pmm",
  },
  {
    code: "46",
    fam: 'autres',
    fr: "Bagarre",
    en: "Fighting",
    sanctions: ["2'", "2+2", "5'", "5+PMM", "10'", "PMM"],
    crit: "<b>Plusieurs coups de poing</b>, lutte réelle, ou altercation difficile à séparer. Instigateur <i>ou</i> agresseur : <b>2' + 5' + PMM</b> ; instigateur <b>et</b> agresseur : <b>2' + 2' + 5' + PMM</b>. Third man in : <b>PMM</b> en plus. Combattant non volontaire : <b>5' seule</b>.",
    fiche: 31,
    ficheTitre: "Bagarre (46)",
    search: "46 bagarre fighting plusieurs coups de poing, lutte reelle, ou altercation difficile a separer. instigateur ou agresseur : 2' + 5' + pmm ; instigateur et agresseur : 2' + 2' + 5' + pmm. third man in : pmm en plus. combattant non volontaire : 5' seule. 2' 2+2 5' 5+pmm 10' pmm",
  },
  {
    code: "47",
    fam: 'coups',
    fr: "Coup de tête",
    en: "Head-butting",
    sanctions: ["2+2", "5+PMM"],
    crit: "Tête ou casque dirigé volontairement vers l'adversaire — la <b>tentative suffit</b>. Tentative ou contact léger → 2'+2' ; selon la gravité → 5' + PMM.",
    fiche: 27,
    ficheTitre: "Coups — le critère",
    search: "47 coup de tete head-butting tete ou casque dirige volontairement vers l'adversaire — la tentative suffit. tentative ou contact leger → 2'+2' ; selon la gravite → 5' + pmm. 2+2 5+pmm",
  },
  {
    code: "48",
    fam: 'charges',
    fr: "Charge contre la tête ou le cou",
    en: "Illegal check to the head",
    sanctions: ["2'", "5+PMM"],
    crit: "<b>Point principal de contact</b>, contact évitable, force, vulnérabilité. <b>Il n'existe pas de bonne charge à la tête</b> : la responsabilité est à celui qui charge. <b>Pas de majeure seule.</b>",
    fiche: 26,
    ficheTitre: "Charges — le critère",
    search: "48 charge contre la tete ou le cou illegal check to the head point principal de contact, contact evitable, force, vulnerabilite. il n'existe pas de bonne charge a la tete : la responsabilite est a celui qui charge. pas de majeure seule. 2' 5+pmm",
  },
  {
    code: "49",
    fam: 'coups',
    fr: "Coup de pied",
    en: "Kicking",
    sanctions: ["5+PMM"],
    crit: "Usage <b>volontaire du patin</b>, mouvement de coup de pied pour frapper ou tenter de frapper. <b>Toujours 5' + PMM.</b>",
    fiche: 27,
    ficheTitre: "Coups — le critère",
    search: "49 coup de pied kicking usage volontaire du patin, mouvement de coup de pied pour frapper ou tenter de frapper. toujours 5' + pmm. 5+pmm",
  },
  {
    code: "50",
    fam: 'coups',
    fr: "Coup de genou",
    en: "Kneeing",
    sanctions: ["2'", "5+PMM"],
    crit: "<b>Jambe ou genou dirigé</b> vers l'extérieur pour entrer en contact. À distinguer du coupage 44.",
    fiche: 27,
    ficheTitre: "Coups — le critère",
    search: "50 coup de genou kneeing jambe ou genou dirige vers l'exterieur pour entrer en contact. a distinguer du coupage 44. 2' 5+pmm",
  },
  {
    code: "51",
    fam: 'autres',
    fr: "Dureté excessive",
    en: "Roughing",
    sanctions: ["2'", "5+PMM"],
    crit: "Coup de poing <b>isolé</b>, petite altercation, riposte sans suite, <b>retrait du casque</b> d'un adversaire → 2' — <b>pas 2'+2'</b> pour en faire une bagarre. Gardien qui frappe avec son bouclier → 5' + PMM.",
    fiche: 31,
    ficheTitre: "Bagarre (46)",
    search: "51 durete excessive roughing coup de poing isole, petite altercation, riposte sans suite, retrait du casque d'un adversaire → 2' — pas 2'+2' pour en faire une bagarre. gardien qui frappe avec son bouclier → 5' + pmm. 2' 5+pmm",
  },
  {
    code: "52",
    fam: 'coups',
    fr: "Balayage",
    en: "Slew-footing",
    sanctions: ["5+PMM"],
    crit: "La <b>jambe fait perdre l'équilibre</b> <u>et</u> le haut du corps est <b>poussé vers l'arrière</b> — ne pas confondre avec un simple faire trébucher.",
    fiche: 27,
    ficheTitre: "Coups — le critère",
    search: "52 balayage slew-footing la jambe fait perdre l'equilibre et le haut du corps est pousse vers l'arriere — ne pas confondre avec un simple faire trebucher. 5+pmm",
  },
  {
    code: "53",
    fam: 'autres',
    fr: "Jet d'équipement",
    en: "Throwing equipment",
    sanctions: ["2'", "PBM", "5+PMM", "TIR", "BUT"],
    crit: "<b>Vers qui, où, avec quel impact ?</b> Objet lancé sur une <b>personne</b> avec risque de blessure → 5' + PMM ; en <b>zone de défense</b> vers le puck → TP. Écarter sa crosse brisée sans gêner le jeu n'est pas une faute.",
    fiche: 18,
    ficheTitre: "Mineures 2' — 2/2",
    search: "53 jet d'equipement throwing equipment vers qui, ou, avec quel impact ? objet lance sur une personne avec risque de blessure → 5' + pmm ; en zone de defense vers le puck → tp. ecarter sa crosse brisee sans gener le jeu n'est pas une faute. 2' pbm 5+pmm tir but",
  },
  {
    code: "54",
    fam: 'destructives',
    fr: "Retenir · retenir la crosse",
    en: "Holding",
    sanctions: ["2'", "TIR", "BUT"],
    crit: "<b>Mains, bras ou corps.</b> Agrippe-t-il l'adversaire ou <b>sa canne</b> ? Une bataille à la bande n'est pas automatiquement un retenir. <b>Jamais de majeure.</b>",
    fiche: 29,
    ficheTitre: "Fautes destructives — le critère",
    search: "54 retenir · retenir la crosse holding mains, bras ou corps. agrippe-t-il l'adversaire ou sa canne ? une bataille a la bande n'est pas automatiquement un retenir. jamais de majeure. 2' tir but",
  },
  {
    code: "55",
    fam: 'destructives',
    fr: "Accrocher",
    en: "Hooking",
    sanctions: ["2'", "5+PMM", "TIR", "BUT"],
    crit: "Crosse utilisée pour <b>retenir le corps</b>. <b>À l'horizontale, c'est un danger.</b> Retient-elle, freine-t-elle, empêche-t-elle de progresser librement ?",
    fiche: 29,
    ficheTitre: "Fautes destructives — le critère",
    search: "55 accrocher hooking crosse utilisee pour retenir le corps. a l'horizontale, c'est un danger. retient-elle, freine-t-elle, empeche-t-elle de progresser librement ? 2' 5+pmm tir but",
  },
  {
    code: "56",
    fam: 'destructives',
    fr: "Obstruction",
    en: "Interference",
    sanctions: ["2'", "PBM", "5'", "5+PMM", "TIR", "BUT"],
    crit: "<b>Qui a le puck ?</b> La position a-t-elle été obtenue <b>légalement</b> ? Se déplace-t-il pour bloquer le chemin ? Aussi depuis le banc.",
    fiche: 29,
    ficheTitre: "Fautes destructives — le critère",
    search: "56 obstruction interference qui a le puck ? la position a-t-elle ete obtenue legalement ? se deplace-t-il pour bloquer le chemin ? aussi depuis le banc. 2' pbm 5' 5+pmm tir but",
  },
  {
    code: "57",
    fam: 'destructives',
    fr: "Faire trébucher",
    en: "Tripping",
    sanctions: ["2'", "5'", "5+PMM", "TIR", "BUT"],
    crit: "<b>Qu'est-ce qui provoque réellement la chute ?</b> Joue-t-il <b>d'abord légalement le puck</b> ? Un joueur qui tombe n'est pas automatiquement victime d'une faute.",
    fiche: 29,
    ficheTitre: "Fautes destructives — le critère",
    search: "57 faire trebucher tripping qu'est-ce qui provoque reellement la chute ? joue-t-il d'abord legalement le puck ? un joueur qui tombe n'est pas automatiquement victime d'une faute. 2' 5' 5+pmm tir but",
  },
  {
    code: "58",
    fam: 'crosse',
    fr: "Harponner avec le bout du manche",
    en: "Butt-ending",
    sanctions: ["2+2", "5+PMM"],
    crit: "Partie du <b>manche au-dessus de la main</b>. Le contact n'est pas nécessaire : <b>tentative → 2'+2'</b>, <b>touché → 5' + PMM</b>.",
    fiche: 28,
    ficheTitre: "Fautes de crosse — le critère",
    search: "58 harponner avec le bout du manche butt-ending partie du manche au-dessus de la main. le contact n'est pas necessaire : tentative → 2'+2', touche → 5' + pmm. 2+2 5+pmm",
  },
  {
    code: "59",
    fam: 'crosse',
    fr: "Cross-check",
    en: "Cross-checking",
    sanctions: ["2'", "5+PMM", "TIR", "BUT"],
    crit: "<b>Manche tenu à deux mains</b> et utilisé pour charger en force. Avoir les deux mains sur la crosse n'est <b>pas automatiquement</b> un cross-check.",
    fiche: 28,
    ficheTitre: "Fautes de crosse — le critère",
    search: "59 cross-check cross-checking manche tenu a deux mains et utilise pour charger en force. avoir les deux mains sur la crosse n'est pas automatiquement un cross-check. 2' 5+pmm tir but",
  },
  {
    code: "60",
    fam: 'crosse',
    fr: "Crosse haute sur un joueur",
    en: "High-sticking",
    sanctions: ["2'", "2+2", "5+PMM"],
    crit: "Contact <b>au-dessus des épaules</b> de l'adversaire. Accidentel <b>avec blessure</b> → 2'+2' ; <b>avec intention</b> → 5' + PMM. Un contact accidentel dans l'armement d'un tir est autorisé. Ne pas confondre avec la règle de jeu 80.",
    fiche: 28,
    ficheTitre: "Fautes de crosse — le critère",
    search: "60 crosse haute sur un joueur high-sticking contact au-dessus des epaules de l'adversaire. accidentel avec blessure → 2'+2' ; avec intention → 5' + pmm. un contact accidentel dans l'armement d'un tir est autorise. ne pas confondre avec la regle de jeu 80. 2' 2+2 5+pmm",
  },
  {
    code: "61",
    fam: 'crosse',
    fr: "Coup de crosse",
    en: "Slashing",
    sanctions: ["2'", "5+PMM", "TIR", "BUT"],
    crit: "<b>Cherche-t-il le puck ou l'adversaire ?</b> Un contact léger sur la <b>cuissette</b>, l'avant des jambières ou le <b>bas de la canne</b> fait partie du jeu.",
    fiche: 28,
    ficheTitre: "Fautes de crosse — le critère",
    search: "61 coup de crosse slashing cherche-t-il le puck ou l'adversaire ? un contact leger sur la cuissette, l'avant des jambieres ou le bas de la canne fait partie du jeu. 2' 5+pmm tir but",
  },
  {
    code: "62",
    fam: 'crosse',
    fr: "Piquage avec la lame",
    en: "Spearing",
    sanctions: ["2+2", "5+PMM"],
    crit: "<b>Pointe de la palette</b> dirigée vers l'adversaire. Le contact n'est pas nécessaire : <b>tentative → 2'+2'</b>, <b>touché → 5' + PMM</b>.",
    fiche: 28,
    ficheTitre: "Fautes de crosse — le critère",
    search: "62 piquage avec la lame spearing pointe de la palette dirigee vers l'adversaire. le contact n'est pas necessaire : tentative → 2'+2', touche → 5' + pmm. 2+2 5+pmm",
  },
  {
    code: "63",
    fam: 'autres',
    fr: "Retarder le jeu",
    en: "Delaying the game",
    sanctions: ["2'", "PBM", "TIR", "BUT"],
    crit: "Puck <b>hors de la glace</b> depuis sa zone de défense, <b>gel volontaire</b>, <b>but déplacé</b>, tomber sur le puck. Gardien <b>sous pression</b> : il peut geler le puck.",
    fiche: 35,
    ficheTitre: "Retarder le jeu (63)",
    search: "63 retarder le jeu delaying the game puck hors de la glace depuis sa zone de defense, gel volontaire, but deplace, tomber sur le puck. gardien sous pression : il peut geler le puck. 2' pbm tir but",
  },
  {
    code: "64",
    fam: 'autres',
    fr: "Plongeon · embellissement",
    en: "Diving / embellishment",
    sanctions: ["2'"],
    crit: "<b>Simulation</b> : pas de faute, le simulateur seul est puni. <b>Embellissement</b> : la faute existe mais la réaction est exagérée → <b>les deux</b> joueurs.",
    fiche: 33,
    ficheTitre: "Simulation & embellissement (64)",
    search: "64 plongeon · embellissement diving / embellishment simulation : pas de faute, le simulateur seul est puni. embellissement : la faute existe mais la reaction est exageree → les deux joueurs. 2'",
  },
  {
    code: "65",
    fam: 'autres',
    fr: "Équipement incorrect",
    en: "Illegal equipment",
    sanctions: ["2'", "10'", "PMM"],
    crit: "<b>Avertissement à l'équipe</b>, valable tout le match. Puis <b>2' par infraction</b> et par joueur, <b>10'</b> si le même joueur recommence, <b>PMM</b> ensuite.",
    fiche: 54,
    ficheTitre: "Équipement incorrect",
    search: "65 equipement incorrect illegal equipment avertissement a l'equipe, valable tout le match. puis 2' par infraction et par joueur, 10' si le meme joueur recommence, pmm ensuite. 2' 10' pmm",
  },
  {
    code: "67",
    fam: 'autres',
    fr: "Puck joué à la main",
    en: "Handling the puck",
    sanctions: ["2'", "TIR", "BUT"],
    crit: "<b>Attraper</b> et patiner, <b>recouvrir</b>, <b>ramasser</b> le puck, ou le jouer à la main <b>lors d'un engagement</b>. Gardien : le garder <b>plus de 3 s sans pression</b>. Se coucher dessus dans sa zone de but → TP.",
    fiche: 45,
    ficheTitre: "Puck à la main — pénalités",
    search: "67 puck joue a la main handling the puck attraper et patiner, recouvrir, ramasser le puck, ou le jouer a la main lors d'un engagement. gardien : le garder plus de 3 s sans pression. se coucher dessus dans sa zone de but → tp. 2' tir but",
  },
  {
    code: "68",
    fam: 'autres',
    fr: "Changement de joueur illégal",
    en: "Illegal substitution",
    sanctions: ["PBM", "TIR", "BUT"],
    crit: "Changement <b>délibéré</b> → <b>tir de pénalité</b>. Substitution <b>prématurée du gardien</b> : arrêt de jeu, <b>sans pénalité</b>.",
    fiche: 11,
    ficheTitre: "Procédure de changement",
    search: "68 changement de joueur illegal illegal substitution changement delibere → tir de penalite. substitution prematuree du gardien : arret de jeu, sans penalite. pbm tir but",
  },
  {
    code: "69",
    fam: 'autres',
    fr: "Obstruction sur le gardien",
    en: "Interference on the goalkeeper",
    sanctions: ["2'", "5'", "5+PMM"],
    crit: "Contact <b>intentionnel</b> → pénalité, que le gardien soit dans ou hors de son territoire. L'attaquant qui l'<b>empêche de se déplacer</b> → <b>but refusé sans pénalité</b>. Poussé par un défenseur : généralement pas de faute.",
    fiche: 43,
    ficheTitre: "Obstruction sur le gardien (69)",
    search: "69 obstruction sur le gardien interference on the goalkeeper contact intentionnel → penalite, que le gardien soit dans ou hors de son territoire. l'attaquant qui l'empeche de se deplacer → but refuse sans penalite. pousse par un defenseur : generalement pas de faute. 2' 5' 5+pmm",
  },
  {
    code: "70",
    fam: 'autres',
    fr: "Quitter le banc",
    en: "Leaving the bench",
    sanctions: ["2'", "PBM", "PMM", "TIR", "BUT"],
    crit: "Sortir <b>trop tôt</b> du banc des pénalités → 2'. Quitter le banc des joueurs sans autorisation → PBM. <b>1er ou 2e</b> à quitter son banc pendant une altercation → <b>PMM</b>. Empêcher ainsi une occasion manifeste de but → tir de pénalité, ou <b>but accordé</b> si le gardien était remplacé par un joueur de champ.",
    fiche: 34,
    ficheTitre: "Quitter le banc (70)",
    search: "70 quitter le banc leaving the bench sortir trop tot du banc des penalites → 2'. quitter le banc des joueurs sans autorisation → pbm. 1er ou 2e a quitter son banc pendant une altercation → pmm. empecher ainsi une occasion manifeste de but → tir de penalite, ou but accorde si le gardien etait remplace par un joueur de champ. 2' pbm pmm tir but",
  },
  {
    code: "72",
    fam: 'autres',
    fr: "Refus de jouer le puck",
    en: "Refusing to play the puck",
    sanctions: ["---"],
    crit: "Une équipe laisse filer le temps → <b>arrêt de jeu, sans pénalité</b>, engagement au point le plus proche.",
    fiche: 46,
    ficheTitre: "Crosse haute · hors du jeu · refus",
    search: "72 refus de jouer le puck refusing to play the puck une equipe laisse filer le temps → arret de jeu, sans penalite, engagement au point le plus proche. ---",
  },
  {
    code: "73",
    fam: 'autres',
    fr: "Refus de commencer le jeu",
    en: "Refusing to start play",
    sanctions: ["PBM", "PMM"],
    crit: "Avertir le capitaine, <b>15 s</b> pour reprendre, sinon PBM ; 2e fois : PBM + <b>PMM au coach</b> ; puis <b>forfait</b>.",
    fiche: 56,
    ficheTitre: "Gestion & communication",
    search: "73 refus de commencer le jeu refusing to start play avertir le capitaine, 15 s pour reprendre, sinon pbm ; 2e fois : pbm + pmm au coach ; puis forfait. pbm pmm",
  },
  {
    code: "74",
    fam: 'autres',
    fr: "Surnombre de joueurs sur la glace",
    en: "Too many players",
    sanctions: ["PBM", "TIR", "BUT"],
    crit: "<b>Ce n'est pas le nombre, c'est qui participe</b> : jouer le puck ou charger pendant le changement. Être <b>touché accidentellement</b> par le puck n'est pas une pénalité.",
    fiche: 11,
    ficheTitre: "Procédure de changement",
    search: "74 surnombre de joueurs sur la glace too many players ce n'est pas le nombre, c'est qui participe : jouer le puck ou charger pendant le changement. etre touche accidentellement par le puck n'est pas une penalite. pbm tir but",
  },
  {
    code: "75",
    fam: 'officiels',
    fr: "Comportement antisportif",
    en: "Unsportsmanlike conduct",
    sanctions: ["2'", "PBM", "10'", "PMM"],
    crit: "Ce qui <b>dépasse les émotions normales</b> du jeu. 2' joueur · PBM si <b>non identifié</b> · 10' s'il persiste après 2' · PMM après 10', insultes graves, ou en fin de match.",
    fiche: 57,
    ficheTitre: "Escalade & officiels",
    search: "75 comportement antisportif unsportsmanlike conduct ce qui depasse les emotions normales du jeu. 2' joueur · pbm si non identifie · 10' s'il persiste apres 2' · pmm apres 10', insultes graves, ou en fin de match. 2' pbm 10' pmm",
  },
  {
    code: "76",
    fam: 'autres',
    fr: "Faute d'engagement",
    en: "Face-off violation",
    sanctions: ["PBM"],
    crit: "<b>Deux chances</b> : le centre est <b>éjecté</b>, puis PBM à la 2e infraction au <b>même engagement</b>. <b>Après un icing, avertissement</b> au lieu de l'éjection.",
    fiche: 41,
    ficheTitre: "Engagements — violations",
    search: "76 faute d'engagement face-off violation deux chances : le centre est ejecte, puis pbm a la 2e infraction au meme engagement. apres un icing, avertissement au lieu de l'ejection. pbm",
  },
  {
    code: "86",
    fam: 'autres',
    fr: "Début du match et des tiers",
    en: "Starting the game / periods",
    sanctions: ["PBM"],
    crit: "Équipes prêtes à <b>0:00</b>, seuls les <b>joueurs de départ</b> sur la glace, <b>pas d'échauffement</b> entre les périodes.",
    fiche: 7,
    ficheTitre: "Durée & structure du match",
    search: "86 debut du match et des tiers starting the game / periods equipes pretes a 0:00, seuls les joueurs de depart sur la glace, pas d'echauffement entre les periodes. pbm",
  },
  {
    code: "90",
    fam: 'autres',
    fr: "Autre infraction",
    en: "Other infraction",
    sanctions: ["selon"],
    crit: "Le code à inscrire quand la faute <b>ne figure pas</b> dans la liste. La sanction reste celle prévue par le livre de règles.",
    fiche: 36,
    ficheTitre: "Codes SIHF — feuille",
    search: "90 autre infraction other infraction le code a inscrire quand la faute ne figure pas dans la liste. la sanction reste celle prevue par le livre de regles. selon",
  },
  {
    code: "91",
    fam: 'charges',
    fr: "Charge illégale (catégories sans mise en échec)",
    en: "Illegal body checking",
    sanctions: ["2'", "5+PMM"],
    crit: "Se <b>déplacer volontairement vers</b> un adversaire pour le charger — <b>U14-A, U16-A, U18-A, 4e ligue romande, féminin</b>. Règle 101. En PFWL et SWHL B, seule la charge <b>nord-sud</b> est interdite.",
    fiche: 30,
    ficheTitre: "Charges autorisées ? (101)",
    search: "91 charge illegale (categories sans mise en echec) illegal body checking se deplacer volontairement vers un adversaire pour le charger — u14-a, u16-a, u18-a, 4e ligue romande, feminin. regle 101. en pfwl et swhl b, seule la charge nord-sud est interdite. 2' 5+pmm",
  },
]
