// Systèmes d'arbitrage — IIHF Officiating Procedure Manual, versions
// « Three Officials System » et « Four Officials System », v1.0 05/2023.
// Généré depuis les fiches sources (projet HockeyReferee) — ne pas éditer à la
// main sans reporter la correction dans la source.
//
// `html` est un fragment statique produit ici, jamais une saisie utilisateur :
// il est injecté tel quel par Sheet.tsx. `search` est le texte de la fiche,
// en minuscules et sans accents, prêt pour le filtre.

export type SystemGroup = 'common' | 's3' | 's4'

export interface SystemCard {
  n: number
  group: SystemGroup
  title: string
  html: string
  search: string
}

export const SYSTEM_GROUPS: {
  key: SystemGroup
  label: string
  short: string
  tone: string
}[] = [
  { key: 'common', label: "Commun aux deux systèmes", short: "Commun", tone: 'th-a' },
  { key: 's3', label: "Système à 3 officiels", short: "3 officiels", tone: 'th-d' },
  { key: 's4', label: "Système à 4 officiels", short: "4 officiels", tone: 'th-b' },
]

export const SYSTEMS: SystemCard[] = [
  {
    n: 1,
    group: 'common',
    title: "Les deux systèmes en un coup d'œil",
    html: "<table class=\"t tx\"> <tr><th> </th><th>3 officiels</th><th>4 officiels</th></tr> <tr><td><b>Équipe</b></td><td>1 arbitre + 2 juges de lignes</td><td>2 arbitres (R1 / R2) + 2 juges de lignes</td></tr> <tr><td><b>Pénalités</b></td><td>un seul décideur</td><td>partagées : le meilleur angle décide</td></tr> <tr><td><b>Patinage</b></td><td>suivre le jeu, surtout vers l'avant</td><td>beaucoup de <b>marche arrière</b>, jeu devant soi</td></tr> <tr><td><b>Zone de fin</b></td><td>positions fixes BOP / ATB / ATN</td><td>4 zones de responsabilité partagées</td></tr> <tr><td><b>Engagement central</b></td><td>l'arbitre</td><td>R1 au début des tiers, sinon un juge de lignes</td></tr> <tr><td><b>Changement de lignes</b></td><td>l'arbitre, selon le lieu de l'engagement</td><td>R2, sur la ligne rouge centrale</td></tr> <tr><td><b>Icing</b></td><td>L1 juge la course, L2 la ligne médiane</td><td>idem + R1 et R2 changent de camp ; L1 devient L2</td></tr> <tr><td><b>Vidéo</b></td><td>non traitée</td><td>procédure complète (VRC, challenge, majeures)</td></tr> </table> <p class=\"src\">IIHF Officiating Procedure Manual, versions 3 et 4 officiels, v1.0 — 05/2023.</p>",
    search: "les deux systemes en un coup d'œil 3 officiels 4 officiels equipe 1 arbitre + 2 juges de lignes 2 arbitres (r1 / r2) + 2 juges de lignes penalites un seul decideur partagees : le meilleur angle decide patinage suivre le jeu, surtout vers l'avant beaucoup de marche arriere , jeu devant soi zone de fin positions fixes bop / atb / atn 4 zones de responsabilite partagees engagement central l'arbitre r1 au debut des tiers, sinon un juge de lignes changement de lignes l'arbitre, selon le lieu de l'engagement r2, sur la ligne rouge centrale icing l1 juge la course, l2 la ligne mediane idem + r1 et r2 changent de camp ; l1 devient l2 video non traitee procedure complete (vrc, challenge, majeures) iihf officiating procedure manual, versions 3 et 4 officiels, v1.0 — 05/2023.",
  },
  {
    n: 2,
    group: 'common',
    title: "Rôles & vocabulaire",
    html: "<table class=\"t sm\"> <tr><td><b>Arbitre</b> <span class=\"mut\">Referee</span> — pénalités et buts. À 4 : <b>R1</b> meneur (<i>leading</i>), le plus proche du jeu ; <b>R2</b> suiveur (<i>trailing</i>), responsable de la zone <b>hors</b> du jeu principal et du soutien à R1.</td></tr> <tr><td><b>L1</b> — juge de lignes avant : <b>hors-jeu</b> sur sa ligne bleue, décision de la <b>course</b> lors d'un icing, soutien près du jeu.</td></tr> <tr><td><b>L2</b> — juge de lignes arrière : <b>ligne médiane</b> pour l'icing, soutien de L1 sur le hors-jeu, contrôle des joueurs hors du jeu principal.</td></tr> <tr><td><b>Disconnected</b> — officiel placé sans bon angle sur sa zone de responsabilité, ou trop loin du jeu.</td></tr> <tr><td><b>Sight line</b> — l'angle de vue de l'officiel vers sa zone de responsabilité.</td></tr> <tr><td><b>Ligne bleue désignée</b> — la ligne dont le juge de lignes répond dans la majorité des situations (fiche 4).</td></tr> <tr><td><b>VRC</b> — Video Review Consultant.</td></tr> </table> <p class=\"src\">Les rôles de L1 et L2 sont <b>identiques</b> dans les deux systèmes.</p>",
    search: "roles & vocabulaire arbitre referee — penalites et buts. a 4 : r1 meneur ( leading ), le plus proche du jeu ; r2 suiveur ( trailing ), responsable de la zone hors du jeu principal et du soutien a r1. l1 — juge de lignes avant : hors-jeu sur sa ligne bleue, decision de la course lors d'un icing, soutien pres du jeu. l2 — juge de lignes arriere : ligne mediane pour l'icing, soutien de l1 sur le hors-jeu, controle des joueurs hors du jeu principal. disconnected — officiel place sans bon angle sur sa zone de responsabilite, ou trop loin du jeu. sight line — l'angle de vue de l'officiel vers sa zone de responsabilite. ligne bleue designee — la ligne dont le juge de lignes repond dans la majorite des situations (fiche 4). vrc — video review consultant. les roles de l1 et l2 sont identiques dans les deux systemes.",
  },
  {
    n: 3,
    group: 'common',
    title: "État d'esprit & priorités",
    html: "<ul> <li><b>Ne pas courir après le jeu</b> (« don't chase the game ») : chercher le <b>meilleur angle</b>, pas la distance la plus courte. Le bon placement se lit à l'avance.</li> <li><b>Hockey IQ</b> : anticiper où la situation va se produire ; les deux manuels en font la compétence centrale, avant la technique de patinage.</li> <li><b>Garder tous les joueurs devant soi</b> ; ne jamais laisser de joueur dans son dos.</li> <li><b>Priorité du juge de lignes</b> : d'abord être en place pour le hors-jeu et l'icing, <b>ensuite</b> soutenir l'arbitre.</li> <li><b>Ne jamais regarder tous la même chose</b> : à 4 comme à 3, deux officiels focalisés sur le puck laissent le reste de la glace sans surveillance.</li> <li><b>Se couvrir mutuellement</b> : si un officiel tombe ou est piégé, un autre reprend sa ligne ou sa zone jusqu'au retour à la normale.</li> <li>Le manuel est un <b>cadre</b>, pas une réponse à chaque situation : s'en écarter est permis quand cela donne un meilleur angle.</li> </ul>",
    search: "etat d'esprit & priorites ne pas courir apres le jeu (« don't chase the game ») : chercher le meilleur angle , pas la distance la plus courte. le bon placement se lit a l'avance. hockey iq : anticiper ou la situation va se produire ; les deux manuels en font la competence centrale, avant la technique de patinage. garder tous les joueurs devant soi ; ne jamais laisser de joueur dans son dos. priorite du juge de lignes : d'abord etre en place pour le hors-jeu et l'icing, ensuite soutenir l'arbitre. ne jamais regarder tous la meme chose : a 4 comme a 3, deux officiels focalises sur le puck laissent le reste de la glace sans surveillance. se couvrir mutuellement : si un officiel tombe ou est piege, un autre reprend sa ligne ou sa zone jusqu'au retour a la normale. le manuel est un cadre , pas une reponse a chaque situation : s'en ecarter est permis quand cela donne un meilleur angle.",
  },
  {
    n: 4,
    group: 'common',
    title: "Ligne bleue désignée",
    html: "<ul> <li>Avant le match, les deux juges de lignes <b>choisissent</b> la ligne bleue dont chacun répond pour la <b>première moitié</b> du match.</li> <li>Changement de responsabilité à la <b>mi-match</b>, à leur discrétion, après communication claire (verbale, visuelle, ou les deux).</li> <li>La ligne désignée suit le côté choisi pour les <b>engagements</b> (fiche 5).</li> <li>Cela n'interdit pas d'<b>échanger</b> : si un partenaire est mal placé, on couvre sa ligne. Après un échange, la ligne reste sous cette responsabilité jusqu'à ce qu'il soit opportun de revenir à la répartition initiale.</li> </ul> <h2>Engagement en zone de fin</h2> <p>Le juge de lignes <b>arrière</b> reprend la ligne bleue de celui qui procède à l'engagement, et <b>reste sur cette ligne</b> jusqu'à ce que le jeu permette l'échange — ou jusqu'à une contre-attaque rapide qui l'oblige à couvrir sa propre ligne.</p> <h2>Engagement au centre</h2> <p>Celui qui ne procède pas à l'engagement <b>suit le jeu</b> pour couvrir tout hors-jeu possible, quitte à prendre la ligne de son partenaire un court moment.</p> <p class=\"src\">Texte identique dans les deux manuels.</p>",
    search: "ligne bleue designee avant le match, les deux juges de lignes choisissent la ligne bleue dont chacun repond pour la premiere moitie du match. changement de responsabilite a la mi-match , a leur discretion, apres communication claire (verbale, visuelle, ou les deux). la ligne designee suit le cote choisi pour les engagements (fiche 5). cela n'interdit pas d' echanger : si un partenaire est mal place, on couvre sa ligne. apres un echange, la ligne reste sous cette responsabilite jusqu'a ce qu'il soit opportun de revenir a la repartition initiale. engagement en zone de fin le juge de lignes arriere reprend la ligne bleue de celui qui procede a l'engagement, et reste sur cette ligne jusqu'a ce que le jeu permette l'echange — ou jusqu'a une contre-attaque rapide qui l'oblige a couvrir sa propre ligne. engagement au centre celui qui ne procede pas a l'engagement suit le jeu pour couvrir tout hors-jeu possible, quitte a prendre la ligne de son partenaire un court moment. texte identique dans les deux manuels.",
  },
  {
    n: 5,
    group: 'common',
    title: "Engagements désignés & remise du puck",
    html: "<h2>Moitié de glace désignée</h2> <ul> <li>Chaque juge de lignes procède aux engagements d'<b>une moitié</b> de la surface, en accord avec sa ligne bleue désignée.</li> <li>Échange des moitiés à la <b>mi-match</b>, comme pour la ligne bleue <span class=\"mut\">(30 minutes / 30 minutes)</span>.</li> <li>Exception de bon sens : si l'autre juge de lignes a le puck et se trouve <b>plus près</b> du point, il procède à l'engagement — la <b>fluidité</b> prime, puis on reprend la répartition.</li> </ul> <h2>Remise du puck après un icing</h2> <ol> <li>Le juge de lignes <b>arrière</b> veille au bon déroulement du changement de joueurs, puis conduit la procédure d'engagement en zone de fin.</li> <li>Le juge de lignes <b>avant</b> ramasse le puck et patine activement vers le point choisi par l'équipe <b>non fautive</b>, remet le puck à celui qui est en charge des engagements de cette moitié de glace.</li> <li>Il repart ensuite en <b>patinage avant actif</b> vers la ligne bleue et prend position en zone neutre pour surveiller la procédure.</li> </ol> <p class=\"src\">Procédure identique dans les deux systèmes. En système à 4, ce transfert s'accompagne d'un échange de rôles L1 / L2 (fiche 25).</p>",
    search: "engagements designes & remise du puck moitie de glace designee chaque juge de lignes procede aux engagements d' une moitie de la surface, en accord avec sa ligne bleue designee. echange des moities a la mi-match , comme pour la ligne bleue (30 minutes / 30 minutes) . exception de bon sens : si l'autre juge de lignes a le puck et se trouve plus pres du point, il procede a l'engagement — la fluidite prime, puis on reprend la repartition. remise du puck apres un icing le juge de lignes arriere veille au bon deroulement du changement de joueurs, puis conduit la procedure d'engagement en zone de fin. le juge de lignes avant ramasse le puck et patine activement vers le point choisi par l'equipe non fautive , remet le puck a celui qui est en charge des engagements de cette moitie de glace. il repart ensuite en patinage avant actif vers la ligne bleue et prend position en zone neutre pour surveiller la procedure. procedure identique dans les deux systemes. en systeme a 4, ce transfert s'accompagne d'un echange de roles l1 / l2 (fiche 25).",
  },
  {
    n: 6,
    group: 'common',
    title: "Mêlée & bagarre",
    html: "<h2>Arbitre(s)</h2> <ul> <li><b>Jamais</b> d'engagement physique avec les joueurs impliqués.</li> <li>Se placer <b>à l'écart</b> de la mêlée mais assez près pour avoir une vue d'ensemble, prononcer les bonnes pénalités et utiliser <b>voix et sifflet</b>.</li> <li><b>Mémoriser les numéros</b> des joueurs impliqués — indispensable si le gardien est impliqué (un joueur devra purger) ou si des joueurs arrivent des bancs.</li> <li>Surveiller les <b>bancs</b> et, en zone de fin, les <b>joueurs de pointe</b> : descendent-ils vers la mêlée, franchissent-ils la ligne haute du cercle ?</li> </ul> <h2>Juges de lignes</h2> <ul> <li><b>Désamorcer</b> activement : voix, présence, puis intervention physique si nécessaire.</li> <li>Toujours travailler <b>en binôme</b> pour séparer ; la communication est la clé.</li> <li><b>La sécurité du juge de lignes passe avant tout</b> : c'est lui qui choisit le moment d'entrer. L'arbitre doit sanctionner tout joueur qui le met en danger.</li> </ul> <p class=\"warn\">Objectif unique : <b>limiter le nombre de joueurs impliqués</b>. Empêcher les autres de se joindre vaut mieux que séparer ceux qui sont déjà engagés.</p> <p class=\"src\">À 4 officiels, en zone de fin, <b>R1</b> appelle et rapporte les pénalités, <b>R2</b> tient les bancs, note les numéros et surveille les joueurs de pointe.</p>",
    search: "melee & bagarre arbitre(s) jamais d'engagement physique avec les joueurs impliques. se placer a l'ecart de la melee mais assez pres pour avoir une vue d'ensemble, prononcer les bonnes penalites et utiliser voix et sifflet . memoriser les numeros des joueurs impliques — indispensable si le gardien est implique (un joueur devra purger) ou si des joueurs arrivent des bancs. surveiller les bancs et, en zone de fin, les joueurs de pointe : descendent-ils vers la melee, franchissent-ils la ligne haute du cercle ? juges de lignes desamorcer activement : voix, presence, puis intervention physique si necessaire. toujours travailler en binome pour separer ; la communication est la cle. la securite du juge de lignes passe avant tout : c'est lui qui choisit le moment d'entrer. l'arbitre doit sanctionner tout joueur qui le met en danger. objectif unique : limiter le nombre de joueurs impliques . empecher les autres de se joindre vaut mieux que separer ceux qui sont deja engages. a 4 officiels, en zone de fin, r1 appelle et rapporte les penalites, r2 tient les bancs, note les numeros et surveille les joueurs de pointe.",
  },
  {
    n: 7,
    group: 'common',
    title: "Tir de pénalité — tronc commun",
    html: "<ul> <li><b>L1 pose le puck</b> sur le point central et <b>reste debout au-dessus</b> jusqu'à ce que tout le monde soit prêt : tireur, gardien, officiels en place, autres joueurs sortis de la glace.</li> <li>L'arbitre vérifie que tout est en place et que <b>L1 a quitté le centre</b>, puis <b>siffle</b> le départ.</li> <li>Un seul officiel signale le <b>but</b> ou le <b>wash-out</b>. Les juges de lignes gardent leur sifflet dans la poche.</li> <li>Après le tir : <b>L1 contrôle les joueurs</b>, <b>L2 récupère le puck</b>.</li> <li>Pendant une séance de tirs au but, les deux juges de lignes <b>alternent</b> les rôles L1 et L2 à chaque tir.</li> <li>Le doute se discute entre officiels, mais la <b>décision finale reste à l'arbitre</b>.</li> </ul> <p class=\"src\">Les positions diffèrent selon le système — fiches 17 et 27.</p>",
    search: "tir de penalite — tronc commun l1 pose le puck sur le point central et reste debout au-dessus jusqu'a ce que tout le monde soit pret : tireur, gardien, officiels en place, autres joueurs sortis de la glace. l'arbitre verifie que tout est en place et que l1 a quitte le centre , puis siffle le depart. un seul officiel signale le but ou le wash-out . les juges de lignes gardent leur sifflet dans la poche. apres le tir : l1 controle les joueurs , l2 recupere le puck . pendant une seance de tirs au but, les deux juges de lignes alternent les roles l1 et l2 a chaque tir. le doute se discute entre officiels, mais la decision finale reste a l'arbitre . les positions different selon le systeme — fiches 17 et 27.",
  },
  {
    n: 8,
    group: 'common',
    title: "Fautes fréquentes & conseils",
    html: "<ul> <li><b>Suivre le puck des yeux à plusieurs</b> : la faute la plus coûteuse. Si deux officiels regardent la même action, personne ne voit le reste.</li> <li><b>Rester collé à la bande derrière le but</b> ou dans les coins : perte de mobilité, vue masquée par le filet, retard sur la contre-attaque.</li> <li><b>Ne pas sortir de la zone d'attaque</b> parce que des joueurs traînent derrière : suivre le jeu, jeter quelques regards en arrière et <b>faire confiance au juge de lignes</b> pour parler à ces joueurs.</li> <li><b>Multiplier les arrêts et les démarrages</b> : préférer un patinage en <b>« huit »</b> avec des virages serrés.</li> <li><b>Après le coup de sifflet</b>, beaucoup d'altercations naissent près du but : se placer à <b>3 m au maximum du filet</b>, tous les joueurs et les deux bancs dans le champ de vision. La présence et la voix désamorcent.</li> <li><b>À l'arrêt de jeu</b>, les juges de lignes regardent d'abord <b>les joueurs</b> : deux joueurs qui se parlent et se défient se séparent avant que cela ne dégénère. Ensuite seulement, changement de lignes et engagement.</li> </ul>",
    search: "fautes frequentes & conseils suivre le puck des yeux a plusieurs : la faute la plus couteuse. si deux officiels regardent la meme action, personne ne voit le reste. rester colle a la bande derriere le but ou dans les coins : perte de mobilite, vue masquee par le filet, retard sur la contre-attaque. ne pas sortir de la zone d'attaque parce que des joueurs trainent derriere : suivre le jeu, jeter quelques regards en arriere et faire confiance au juge de lignes pour parler a ces joueurs. multiplier les arrets et les demarrages : preferer un patinage en « huit » avec des virages serres. apres le coup de sifflet , beaucoup d'altercations naissent pres du but : se placer a 3 m au maximum du filet , tous les joueurs et les deux bancs dans le champ de vision. la presence et la voix desamorcent. a l'arret de jeu , les juges de lignes regardent d'abord les joueurs : deux joueurs qui se parlent et se defient se separent avant que cela ne degenere. ensuite seulement, changement de lignes et engagement.",
  },
  {
    n: 9,
    group: 's3',
    title: "Système à 3 — vue d'ensemble",
    html: "<ul> <li><b>1 arbitre + 2 juges de lignes.</b> Le système le plus traditionnel : les autres systèmes construisent leurs procédures sur cette base. Qui le maîtrise s'adapte à tous les autres.</li> <li>Pour l'arbitre, le poste est <b>solitaire</b> : toute la responsabilité des pénalités repose sur lui. Le soutien des juges de lignes rend les situations difficiles gérables.</li> <li>Exigence n°1 : la <b>mobilité</b> pour obtenir l'angle parfait tout en couvrant le plus de glace possible — sans devenir un arbitre qui « court après le jeu ».</li> <li>L'arbitre ne siffle <b>ni hors-jeu ni icing</b> ; exception rare : si le juge de lignes est manifestement masqué ou hors position, il peut arrêter le jeu.</li> <li>Si un juge de lignes tombe ou est piégé, l'autre couvre <b>les deux lignes</b> ; si l'arbitre est hors position, un juge de lignes entre en zone et applique le placement de zone de fin jusqu'à son retour.</li> </ul>",
    search: "systeme a 3 — vue d'ensemble 1 arbitre + 2 juges de lignes. le systeme le plus traditionnel : les autres systemes construisent leurs procedures sur cette base. qui le maitrise s'adapte a tous les autres. pour l'arbitre, le poste est solitaire : toute la responsabilite des penalites repose sur lui. le soutien des juges de lignes rend les situations difficiles gerables. exigence n°1 : la mobilite pour obtenir l'angle parfait tout en couvrant le plus de glace possible — sans devenir un arbitre qui « court apres le jeu ». l'arbitre ne siffle ni hors-jeu ni icing ; exception rare : si le juge de lignes est manifestement masque ou hors position, il peut arreter le jeu. si un juge de lignes tombe ou est piege, l'autre couvre les deux lignes ; si l'arbitre est hors position, un juge de lignes entre en zone et applique le placement de zone de fin jusqu'a son retour.",
  },
  {
    n: 10,
    group: 's3',
    title: "Changement de lignes (3 officiels)",
    html: "<p class=\"src\">L'essentiel : une position <b>dégagée et visible</b>, en bon contact avec les deux bancs. La position de départ dépend du lieu du prochain engagement.</p> <table class=\"t tx\"> <tr><td><b>Engagement au centre</b></td><td>procédure conduite au centre de la glace, environ <b>1 m</b> vers les bancs des joueurs pour garder le contact</td></tr> <tr><td><b>Engagement en zone neutre</b></td><td>côté <b>opposé</b> au point d'engagement, entre le point de la zone neutre et celui de la zone de fin — déjà proche de la position de départ qui suivra</td></tr> <tr><td><b>Engagement en zone de fin</b></td><td>au <b>haut du cercle</b>, du côté opposé au point d'engagement ; ensuite, patinage actif pour rejoindre la position de base (BOP)</td></tr> </table> <p>Pendant toute la procédure, les juges de lignes gardent le <b>contrôle des joueurs</b> et se placent rapidement pour l'engagement qui suit.</p>",
    search: "changement de lignes (3 officiels) l'essentiel : une position degagee et visible , en bon contact avec les deux bancs. la position de depart depend du lieu du prochain engagement. engagement au centre procedure conduite au centre de la glace, environ 1 m vers les bancs des joueurs pour garder le contact engagement en zone neutre cote oppose au point d'engagement, entre le point de la zone neutre et celui de la zone de fin — deja proche de la position de depart qui suivra engagement en zone de fin au haut du cercle , du cote oppose au point d'engagement ; ensuite, patinage actif pour rejoindre la position de base (bop) pendant toute la procedure, les juges de lignes gardent le controle des joueurs et se placent rapidement pour l'engagement qui suit.",
  },
  {
    n: 11,
    group: 's3',
    title: "Arbitre — positions d'engagement",
    html: "<h2>Point central</h2> <p>Côté <b>banc des marqueurs</b>, à environ <b>3 m de la bande</b> et <b>1,5 m</b> de part et d'autre de la ligne rouge, pour ne pas masquer la vue du juge de lignes. Meilleure ligne de vue sur le jeu et départ rapide dans les deux directions.</p> <h2>Quatre points de la zone neutre</h2> <p>Côté <b>opposé</b> de la glace, environ <b>1,5 m à l'intérieur</b> de la ligne bleue et <b>1,5 à 3 m</b> de la bande. Si le jeu descend, l'arbitre suit vite et prend le placement de zone ; s'il remonte, il est assez éloigné de la bande pour ne pas percuter le juge de lignes.</p> <h2>Zone de fin</h2> <p>Position de base <b>BOP</b> (fiche 12) : prêt pour une action près du filet, vue excellente sur la ligne de but, hors trajectoire d'un tir.</p> <h2>Faute d'engagement</h2> <p>Sur un <b>premier avertissement</b>, l'arbitre <b>ne se déplace pas</b> du côté de l'engagement : il avertit l'équipe fautive qu'une seconde violation sera pénalisée. Le juge de lignes lui laisse le temps d'avertir et de reprendre sa position.</p>",
    search: "arbitre — positions d'engagement point central cote banc des marqueurs , a environ 3 m de la bande et 1,5 m de part et d'autre de la ligne rouge, pour ne pas masquer la vue du juge de lignes. meilleure ligne de vue sur le jeu et depart rapide dans les deux directions. quatre points de la zone neutre cote oppose de la glace, environ 1,5 m a l'interieur de la ligne bleue et 1,5 a 3 m de la bande. si le jeu descend, l'arbitre suit vite et prend le placement de zone ; s'il remonte, il est assez eloigne de la bande pour ne pas percuter le juge de lignes. zone de fin position de base bop (fiche 12) : pret pour une action pres du filet, vue excellente sur la ligne de but, hors trajectoire d'un tir. faute d'engagement sur un premier avertissement , l'arbitre ne se deplace pas du cote de l'engagement : il avertit l'equipe fautive qu'une seconde violation sera penalisee. le juge de lignes lui laisse le temps d'avertir et de reprendre sa position.",
  },
  {
    n: 12,
    group: 's3',
    title: "Zone de fin — BOP / ATB / ATN",
    html: "<figure class=\"fig\"><img src=\"@/systems/3-zone-de-fin.png\" alt=\"L'arbitre en position de base dans la zone de fin, avec les reperes BOP et ATN\" loading=\"lazy\" decoding=\"async\"><figcaption>Manuel 3 officiels, figure 5</figcaption></figure> <table class=\"t tx\"> <tr><td><b>BOP</b><br><span class=\"mut\">Base of Operations</span></td> <td>Entre la <b>ligne de but</b> et le <b>cercle d'engagement</b>, et entre la position « à la bande » et le poteau le plus proche. <b>Position à occuper le plus souvent possible</b> quand le jeu est en zone.</td></tr> <tr><td><b>ATB</b><br><span class=\"mut\">At the Boards</span></td> <td>À <b>15-20 cm</b> de la bande, à mi-chemin entre la ligne de but et les <i>hash marks</i> du cercle.</td></tr> <tr><td><b>ATN</b><br><span class=\"mut\">At the Net</span></td> <td>Autour du filet, là où l'on voit le mieux si le puck franchit la ligne — idéalement au <b>coin du but</b>, à <b>0,6-1 m</b> de la ligne de but.</td></tr> </table> <ul> <li><b>Éviter</b> la zone derrière la ligne de but et les coins : mobilité perdue, vue masquée par le filet, retard garanti sur une sortie de zone rapide.</li> <li>Si le filet masque le puck dans le coin opposé depuis le BOP, faire <b>un pas vers le point d'engagement</b> pour rouvrir l'angle — sans entrer dans le « no man's land ».</li> <li>Le puck entre du <b>côté de l'arbitre</b> : entrer le long de la bande vers ATB et y rester tant que le puck reste de ce côté. Le puck entre du <b>côté opposé</b> : entrer par la bande puis passer de ATB à BOP.</li> </ul>",
    search: "zone de fin — bop / atb / atn manuel 3 officiels, figure 5 bop base of operations entre la ligne de but et le cercle d'engagement , et entre la position « a la bande » et le poteau le plus proche. position a occuper le plus souvent possible quand le jeu est en zone. atb at the boards a 15-20 cm de la bande, a mi-chemin entre la ligne de but et les hash marks du cercle. atn at the net autour du filet, la ou l'on voit le mieux si le puck franchit la ligne — idealement au coin du but , a 0,6-1 m de la ligne de but. eviter la zone derriere la ligne de but et les coins : mobilite perdue, vue masquee par le filet, retard garanti sur une sortie de zone rapide. si le filet masque le puck dans le coin oppose depuis le bop, faire un pas vers le point d'engagement pour rouvrir l'angle — sans entrer dans le « no man's land ». le puck entre du cote de l'arbitre : entrer le long de la bande vers atb et y rester tant que le puck reste de ce cote. le puck entre du cote oppose : entrer par la bande puis passer de atb a bop.",
  },
  {
    n: 13,
    group: 's3',
    title: "Le Bump, le Pivot, les couloirs",
    html: "<h2>Deux manœuvres</h2> <ul> <li><b>Le Bump</b> — quand le jeu remonte la bande vers l'arbitre placé en ATB : se décaler <b>à l'opposé du jeu</b> le long de la bande (vers le haut ou vers le bas) jusqu'aux <i>hash marks</i> ou à la ligne de but.</li> <li><b>Le Pivot</b> — un appui vers l'extérieur, croiser dessous, puis revenir en <b>marche arrière</b> en position ATB une fois le jeu passé derrière soi. De là, suivre le jeu qui remonte ou continuer à le regarder en zone.</li> </ul> <figure class=\"fig\"><img src=\"@/systems/3-couloirs.png\" alt=\"Les couloirs de patinage : bleu pour l'arbitre, jaune pour les juges de lignes, rouge interdit\" loading=\"lazy\" decoding=\"async\"><figcaption>Manuel 3 officiels, figure 9</figcaption></figure> <h2>Couloirs de patinage</h2> <ul> <li>En remontant la glace, l'arbitre reste dans <b>son couloir</b> (le long de sa bande) ; le couloir central ne s'utilise pas.</li> <li><b>Pas de traversée</b> d'un côté à l'autre pendant que le jeu se déroule. Le changement de côté se fait à l'<b>arrêt de jeu</b>, selon le lieu de l'engagement.</li> </ul> <p class=\"warn\"><b>Exception réservée aux arbitres expérimentés</b> : le passage <b>derrière le filet</b> pour gagner une meilleure position au but et rester hors du jeu. À utiliser rarement, seulement quand le jeu le dicte et que c'est sûr.</p>",
    search: "le bump, le pivot, les couloirs deux manœuvres le bump — quand le jeu remonte la bande vers l'arbitre place en atb : se decaler a l'oppose du jeu le long de la bande (vers le haut ou vers le bas) jusqu'aux hash marks ou a la ligne de but. le pivot — un appui vers l'exterieur, croiser dessous, puis revenir en marche arriere en position atb une fois le jeu passe derriere soi. de la, suivre le jeu qui remonte ou continuer a le regarder en zone. manuel 3 officiels, figure 9 couloirs de patinage en remontant la glace, l'arbitre reste dans son couloir (le long de sa bande) ; le couloir central ne s'utilise pas. pas de traversee d'un cote a l'autre pendant que le jeu se deroule. le changement de cote se fait a l' arret de jeu , selon le lieu de l'engagement. exception reservee aux arbitres experimentes : le passage derriere le filet pour gagner une meilleure position au but et rester hors du jeu. a utiliser rarement, seulement quand le jeu le dicte et que c'est sur.",
  },
  {
    n: 14,
    group: 's3',
    title: "Suivre le jeu — distances",
    html: "<ul> <li>Après l'engagement au centre, <b>regagner la bande au plus vite</b> : au milieu de la glace, une partie des joueurs est dans le dos de l'arbitre.</li> <li>Puck devant soi au centre : reculer <b>le long de la ligne rouge</b> vers la bande. Puck passé derrière soi : <b>pivoter</b>, puis reculer vers la bande opposée au puck.</li> <li>Puck en zone de fin : suivre en <b>angle</b> vers la bande de fond et prendre le placement de zone.</li> </ul> <h2>Sortie de zone</h2> <table class=\"t tx\"> <tr><td><b>Puck du côté opposé</b></td><td><b>2 à 4 m</b> de la bande, <b>6 à 8 m</b> derrière le jeu</td></tr> <tr><td><b>Puck du même côté</b></td><td><b>1 à 1,5 m</b> de la bande, <b>8 à 10 m</b> derrière le jeu</td></tr> </table> <p>Rester près de la bande quand le puck est du même côté garantit trois choses : aucun joueur dans le dos, aucune gêne pour le jeu, et une protection en cas de contact inévitable — plus sûr qu'un choc en pleine glace.</p> <p class=\"src\">Garder la bonne distance donne la perspective sur tous les joueurs et laisse la place nécessaire si le jeu repart dans l'autre sens.</p>",
    search: "suivre le jeu — distances apres l'engagement au centre, regagner la bande au plus vite : au milieu de la glace, une partie des joueurs est dans le dos de l'arbitre. puck devant soi au centre : reculer le long de la ligne rouge vers la bande. puck passe derriere soi : pivoter , puis reculer vers la bande opposee au puck. puck en zone de fin : suivre en angle vers la bande de fond et prendre le placement de zone. sortie de zone puck du cote oppose 2 a 4 m de la bande, 6 a 8 m derriere le jeu puck du meme cote 1 a 1,5 m de la bande, 8 a 10 m derriere le jeu rester pres de la bande quand le puck est du meme cote garantit trois choses : aucun joueur dans le dos, aucune gene pour le jeu, et une protection en cas de contact inevitable — plus sur qu'un choc en pleine glace. garder la bonne distance donne la perspective sur tous les joueurs et laisse la place necessaire si le jeu repart dans l'autre sens.",
  },
  {
    n: 15,
    group: 's3',
    title: "Juges de lignes — en cours de jeu",
    html: "<ul> <li>Toujours être en position de <b>juger l'action</b> : la bonne ligne de vue crée la confiance.</li> <li>Être <b>sur sa ligne bleue</b> (ou légèrement à l'intérieur) pour voir la ligne sans obstacle — c'est le « <b>working the line</b> » au moment où le puck la franchit.</li> <li><b>Ne pas</b> chevaucher la ligne ni se mettre en danger en sautant sur la bande.</li> <li>Zone de travail : de sa ligne bleue jusqu'à mi-chemin entre la ligne rouge centrale et l'autre ligne bleue.</li> <li>Le juge de lignes <b>arrière</b> se place <b>toujours</b> à la hauteur du joueur offensif le plus profond, pour couvrir sa ligne en cas de contre-attaque ou de longue passe.</li> </ul> <figure class=\"fig\"><img src=\"@/systems/3-juges-de-lignes.png\" alt=\"L1 sur sa ligne bleue et L2 a mi-chemin de la ligne rouge, cote oppose\" loading=\"lazy\" decoding=\"async\"><figcaption>Manuel 3 officiels, figure 15</figcaption></figure> <h2>Jeu en zone de fin</h2> <ul> <li><b>L1</b> : un coup de patin à l'extérieur de la ligne bleue, corps orienté à <b>45°</b> pour embrasser toute la zone.</li> <li><b>L2</b> : à mi-chemin entre cette ligne bleue et la ligne rouge, du côté opposé. Quand la défense récupère, L2 anticipe la sortie et <b>recule vers la ligne rouge</b> : les deux lignes bleues sont alors couvertes.</li> <li>L1 surveille les attaquants restés derrière le jeu et doit pouvoir <b>revenir à temps</b> sur sa ligne si le jeu se retourne. Une fois le puck sorti, L2 monte sur la ligne bleue d'attaque.</li> <li>Quand le puck approche d'une ligne bleue, <b>le juge de lignes doit y être avant le puck</b> ; l'autre remonte à mi-chemin entre la ligne rouge et la bleue.</li> </ul>",
    search: "juges de lignes — en cours de jeu toujours etre en position de juger l'action : la bonne ligne de vue cree la confiance. etre sur sa ligne bleue (ou legerement a l'interieur) pour voir la ligne sans obstacle — c'est le « working the line » au moment ou le puck la franchit. ne pas chevaucher la ligne ni se mettre en danger en sautant sur la bande. zone de travail : de sa ligne bleue jusqu'a mi-chemin entre la ligne rouge centrale et l'autre ligne bleue. le juge de lignes arriere se place toujours a la hauteur du joueur offensif le plus profond, pour couvrir sa ligne en cas de contre-attaque ou de longue passe. manuel 3 officiels, figure 15 jeu en zone de fin l1 : un coup de patin a l'exterieur de la ligne bleue, corps oriente a 45° pour embrasser toute la zone. l2 : a mi-chemin entre cette ligne bleue et la ligne rouge, du cote oppose. quand la defense recupere, l2 anticipe la sortie et recule vers la ligne rouge : les deux lignes bleues sont alors couvertes. l1 surveille les attaquants restes derriere le jeu et doit pouvoir revenir a temps sur sa ligne si le jeu se retourne. une fois le puck sorti, l2 monte sur la ligne bleue d'attaque. quand le puck approche d'une ligne bleue, le juge de lignes doit y etre avant le puck ; l'autre remonte a mi-chemin entre la ligne rouge et la bleue.",
  },
  {
    n: 16,
    group: 's3',
    title: "Juges de lignes — engagements",
    html: "<h2>Engagement au centre (arbitre)</h2> <p>Les deux juges de lignes sont de <b>part et d'autre</b> de la glace, contre la bande, <b>juste à l'extérieur</b> des lignes bleues.</p> <h2>Points de la zone neutre</h2> <ul> <li><b>L2</b> suit toujours le jeu et couvre la ligne bleue d'attaque ; <b>L1</b> prend le rôle de juge arrière, entre la ligne bleue et la ligne rouge.</li> <li>Celui qui procède à l'engagement fait <b>face au banc des marqueurs</b>, pour que le chronométreur puisse déclencher l'horloge au lâcher du puck.</li> <li>Celui qui est du côté du banc des marqueurs répond de <b>toutes les lignes</b> si son partenaire se retrouve piégé au milieu de la glace.</li> </ul> <h2>Zone de fin</h2> <ul> <li><b>L2</b> : un coup de patin à l'extérieur de la ligne bleue, côté opposé. Si l'arbitre est masqué et ne voit pas les joueurs derrière L1, L2 peut <b>s'écarter de la bande</b> ce qu'il faut pour dégager la vue.</li> <li>Joueur qui <b>empiète</b> : L2 siffle et lève le bras légèrement plié, <b>paume ouverte</b>, du côté de l'équipe fautive.</li> <li>Après le lâcher, L2 revient contre la bande à un coup de patin de la ligne bleue et y reste ; L1 remonte à mi-chemin entre la ligne rouge et la ligne bleue.</li> </ul>",
    search: "juges de lignes — engagements engagement au centre (arbitre) les deux juges de lignes sont de part et d'autre de la glace, contre la bande, juste a l'exterieur des lignes bleues. points de la zone neutre l2 suit toujours le jeu et couvre la ligne bleue d'attaque ; l1 prend le role de juge arriere, entre la ligne bleue et la ligne rouge. celui qui procede a l'engagement fait face au banc des marqueurs , pour que le chronometreur puisse declencher l'horloge au lacher du puck. celui qui est du cote du banc des marqueurs repond de toutes les lignes si son partenaire se retrouve piege au milieu de la glace. zone de fin l2 : un coup de patin a l'exterieur de la ligne bleue, cote oppose. si l'arbitre est masque et ne voit pas les joueurs derriere l1, l2 peut s'ecarter de la bande ce qu'il faut pour degager la vue. joueur qui empiete : l2 siffle et leve le bras legerement plie, paume ouverte , du cote de l'equipe fautive. apres le lacher, l2 revient contre la bande a un coup de patin de la ligne bleue et y reste ; l1 remonte a mi-chemin entre la ligne rouge et la ligne bleue.",
  },
  {
    n: 17,
    group: 's3',
    title: "Tir de pénalité (3 officiels)",
    html: "<table class=\"t tx\"> <tr><td><b>Arbitre</b></td><td>au but, du <b>côté du banc des marqueurs</b>. Surveille le <b>tireur</b>, le gardien et le franchissement de la ligne.</td></tr> <tr><td><b>L2</b></td><td>de l'<b>autre côté du but</b>, en soutien de l'arbitre.</td></tr> <tr><td><b>L1</b></td><td>pose le puck au centre et reste debout au-dessus jusqu'à ce que tout soit prêt, puis se place <b>entre les bancs</b>, en zone neutre.</td></tr> </table> <ul> <li>L'arbitre vérifie que <b>L1 a quitté le centre</b>, puis siffle le départ.</li> <li><b>Seul l'arbitre</b> signale le but ou le wash-out ; les juges de lignes gardent leur sifflet dans la poche.</li> <li>Il peut consulter les juges de lignes sur une situation peu claire, mais <b>tranche seul</b>.</li> <li>Après le tir : <b>L1 contrôle les joueurs</b>, <b>L2 prend le puck</b>. En séance de tirs au but, les deux alternent les rôles.</li> </ul>",
    search: "tir de penalite (3 officiels) arbitre au but, du cote du banc des marqueurs . surveille le tireur , le gardien et le franchissement de la ligne. l2 de l' autre cote du but , en soutien de l'arbitre. l1 pose le puck au centre et reste debout au-dessus jusqu'a ce que tout soit pret, puis se place entre les bancs , en zone neutre. l'arbitre verifie que l1 a quitte le centre , puis siffle le depart. seul l'arbitre signale le but ou le wash-out ; les juges de lignes gardent leur sifflet dans la poche. il peut consulter les juges de lignes sur une situation peu claire, mais tranche seul . apres le tir : l1 controle les joueurs , l2 prend le puck . en seance de tirs au but, les deux alternent les roles.",
  },
  {
    n: 18,
    group: 's4',
    title: "Système à 4 — vue d'ensemble",
    html: "<h2>Ce qui change par rapport au système à 3</h2> <ul> <li>Le jeu se déroule <b>devant</b> l'arbitre bien plus souvent, au lieu d'être suivi de derrière.</li> <li><b>Beaucoup plus de patinage arrière</b> : exigence technique supérieure.</li> <li>La responsabilité des pénalités est <b>partagée entre deux arbitres</b> — plus de sécurité perçue pour les joueurs comme pour l'équipe d'arbitrage.</li> <li>Communication avec les équipes et les bancs <b>plus efficace</b>.</li> </ul> <h2>Avantages</h2> <ul> <li>Plus de surface couverte par l'équipe d'arbitrage.</li> <li>Zones de responsabilité <b>plus claires</b> pour chacun.</li> <li>De meilleures lignes de vue, donc des décisions plus justes.</li> </ul> <p class=\"src\"><b>Historique</b> — NHL : déploiement progressif de 1998-99 à 2000-01. IIHF : introduit sur la scène internationale en <b>2008</b> (Mondial au Canada et Mondial U20 en République tchèque).</p>",
    search: "systeme a 4 — vue d'ensemble ce qui change par rapport au systeme a 3 le jeu se deroule devant l'arbitre bien plus souvent, au lieu d'etre suivi de derriere. beaucoup plus de patinage arriere : exigence technique superieure. la responsabilite des penalites est partagee entre deux arbitres — plus de securite percue pour les joueurs comme pour l'equipe d'arbitrage. communication avec les equipes et les bancs plus efficace . avantages plus de surface couverte par l'equipe d'arbitrage. zones de responsabilite plus claires pour chacun. de meilleures lignes de vue, donc des decisions plus justes. historique — nhl : deploiement progressif de 1998-99 a 2000-01. iihf : introduit sur la scene internationale en 2008 (mondial au canada et mondial u20 en republique tcheque).",
  },
  {
    n: 19,
    group: 's4',
    title: "R1 et R2 — rôles",
    html: "<ul> <li><b>R1</b>, arbitre <b>meneur</b> : le plus proche de l'aire de jeu, responsable de la zone d'action directe.</li> <li><b>R2</b>, arbitre <b>suiveur</b> : responsable de tout ce qui se passe <b>hors</b> du jeu principal, et soutien de R1.</li> <li>Les deux ont <b>la même autorité</b> sur la glace. Les rôles s'échangent en permanence selon le sens du jeu : celui qui monte devient R1.</li> <li>La réussite du système tient à la <b>coopération</b> : ni deviner, ni siffler ce qu'on n'a pas vu, mais ne pas se laisser porter et laisser son partenaire tout appeler.</li> <li>Quand R1 se déplace vers la position de R2, il ne doit <b>laisser aucun joueur dans son dos</b>.</li> <li>Si R1 est <b>piégé dans le coin</b>, R2 se déplace vers le centre de la glace pour prendre l'angle qui manque.</li> </ul> <p class=\"src\">R2 est souvent <b>loin</b> du jeu principal : les juges de lignes doivent alors soutenir la couverture des zones d'action.</p>",
    search: "r1 et r2 — roles r1 , arbitre meneur : le plus proche de l'aire de jeu, responsable de la zone d'action directe. r2 , arbitre suiveur : responsable de tout ce qui se passe hors du jeu principal, et soutien de r1. les deux ont la meme autorite sur la glace. les roles s'echangent en permanence selon le sens du jeu : celui qui monte devient r1. la reussite du systeme tient a la cooperation : ni deviner, ni siffler ce qu'on n'a pas vu, mais ne pas se laisser porter et laisser son partenaire tout appeler. quand r1 se deplace vers la position de r2, il ne doit laisser aucun joueur dans son dos . si r1 est piege dans le coin , r2 se deplace vers le centre de la glace pour prendre l'angle qui manque. r2 est souvent loin du jeu principal : les juges de lignes doivent alors soutenir la couverture des zones d'action.",
  },
  {
    n: 20,
    group: 's4',
    title: "Engagement au centre (4 officiels)",
    html: "<p class=\"src\">Le juge de lignes conduit <b>tous</b> les engagements au point central, sauf au <b>début de chaque tiers</b> du temps réglementaire, où c'est R1. L'engagement d'ouverture de la <b>prolongation</b> est conduit par le juge de lignes.</p> <p class=\"box\">Engagement au centre uniquement dans quatre cas : <b>début de tiers</b>, <b>après un but</b>, <b>changement prématuré du gardien</b> (quand la règle le permet), <b>icing annoncé à tort</b>. Partout ailleurs, on utilise le bon point de la zone concernée.</p> <h2>Début de tiers — R1 engage</h2> <ul> <li><b>R1</b> face au banc des marqueurs ; <b>R2</b> entre la ligne rouge et la ligne bleue, face à R1 et aux bancs.</li> <li><b>L2</b> sur la même ligne bleue que R2 mais du côté opposé ; <b>L1</b> en <b>diagonale</b> de L2.</li> <li><b>R2 et L1 ne doivent pas</b> se retrouver sur la même ligne bleue ou le même point : cela réduit le nombre d'angles de vue.</li> <li>Responsabilités : R1 les deux joueurs de l'engagement ; R2 les joueurs dans le dos de R1 ; L1 et L2 les ailiers à l'extérieur du cercle.</li> <li>Après le lâcher, R1 quitte le cercle vers <b>l'extrémité opposée</b> au sens du jeu et R2 suit le jeu : les deux <b>échangent leurs rôles</b>. R1 peut être <i>disconnected</i> en sortant du cercle — les juges de lignes couvrent.</li> </ul> <h2>Autres cas — L1 engage</h2> <ul> <li>Après un but, <b>R1 se place à l'extérieur du banc de l'équipe qui a marqué</b>, conduit le changement de lignes et surveille la validation du but (juge de but ou lampe de révision).</li> <li>R1 et R2 aux points de la zone neutre, <b>en diagonale</b> l'un de l'autre.</li> <li><b>L1</b> engage face au banc des marqueurs ; <b>L2</b> sur la ligne rouge, prêt à suivre le jeu et à aider sur la ligne bleue désignée.</li> <li>Si un arbitre voit un hors-jeu que le juge de lignes ne peut pas voir, il <b>arrête le jeu et signale</b> le hors-jeu.</li> </ul>",
    search: "engagement au centre (4 officiels) le juge de lignes conduit tous les engagements au point central, sauf au debut de chaque tiers du temps reglementaire, ou c'est r1. l'engagement d'ouverture de la prolongation est conduit par le juge de lignes. engagement au centre uniquement dans quatre cas : debut de tiers , apres un but , changement premature du gardien (quand la regle le permet), icing annonce a tort . partout ailleurs, on utilise le bon point de la zone concernee. debut de tiers — r1 engage r1 face au banc des marqueurs ; r2 entre la ligne rouge et la ligne bleue, face a r1 et aux bancs. l2 sur la meme ligne bleue que r2 mais du cote oppose ; l1 en diagonale de l2. r2 et l1 ne doivent pas se retrouver sur la meme ligne bleue ou le meme point : cela reduit le nombre d'angles de vue. responsabilites : r1 les deux joueurs de l'engagement ; r2 les joueurs dans le dos de r1 ; l1 et l2 les ailiers a l'exterieur du cercle. apres le lacher, r1 quitte le cercle vers l'extremite opposee au sens du jeu et r2 suit le jeu : les deux echangent leurs roles . r1 peut etre disconnected en sortant du cercle — les juges de lignes couvrent. autres cas — l1 engage apres un but, r1 se place a l'exterieur du banc de l'equipe qui a marque , conduit le changement de lignes et surveille la validation du but (juge de but ou lampe de revision). r1 et r2 aux points de la zone neutre, en diagonale l'un de l'autre. l1 engage face au banc des marqueurs ; l2 sur la ligne rouge, pret a suivre le jeu et a aider sur la ligne bleue designee. si un arbitre voit un hors-jeu que le juge de lignes ne peut pas voir, il arrete le jeu et signale le hors-jeu.",
  },
  {
    n: 21,
    group: 's4',
    title: "Engagements zone de fin & neutre",
    html: "<h2>Zone de fin</h2> <ul> <li><b>R1</b> vers le point d'engagement opposé ; <b>R2</b> en <b>diagonale</b>, de l'autre côté de la glace, juste à l'extérieur de la ligne bleue.</li> <li><b>L1</b> au point, conduit l'engagement ; <b>L2</b> du côté opposé, hors de la ligne bleue, dans la meilleure ligne de vue possible.</li> <li>Responsabilités : <b>R1</b> les joueurs <b>devant</b> L1 ; <b>R2</b> les joueurs <b>dans le dos</b> de L1 ; les deux surveillent aussi les joueurs qui engagent. <b>L2</b> soutient L1 et R2 ; après le lâcher, L1 aide R1 sur les joueurs juste devant lui.</li> <li>L1 ne se précipite <b>pas</b> vers la zone neutre : d'abord le contrôle des joueurs et un chemin dégagé — L2 assure pendant ce temps.</li> <li>R2 peut utiliser sa position devant les bancs pour <b>communiquer</b> avec les équipes.</li> </ul> <h2>Zone neutre</h2> <ul> <li><b>R1</b> près du haut du cercle ; <b>R2</b> en diagonale de R1, du même côté de l'engagement, proche de la ligne bleue.</li> <li><b>L1</b> au point ; <b>L2</b> sur le point d'engagement opposé.</li> <li>Responsabilités : <b>R1</b> les joueurs dans le dos de L1, <b>R2</b> ceux devant lui ; <b>L2</b> les ailiers devant L1 <b>et</b> la ligne bleue pour un hors-jeu.</li> <li>Les deux arbitres sont prêts à <b>partir dans la zone</b> correspondant au sens du jeu ; L2 suit le jeu et couvre la ligne rouge pour l'icing, puis la ligne bleue éloignée.</li> </ul> <p class=\"src\">Principe constant : les positions se choisissent pour <b>maximiser les angles</b> vers la zone de responsabilité de chacun, jamais pour se ranger symétriquement.</p>",
    search: "engagements zone de fin & neutre zone de fin r1 vers le point d'engagement oppose ; r2 en diagonale , de l'autre cote de la glace, juste a l'exterieur de la ligne bleue. l1 au point, conduit l'engagement ; l2 du cote oppose, hors de la ligne bleue, dans la meilleure ligne de vue possible. responsabilites : r1 les joueurs devant l1 ; r2 les joueurs dans le dos de l1 ; les deux surveillent aussi les joueurs qui engagent. l2 soutient l1 et r2 ; apres le lacher, l1 aide r1 sur les joueurs juste devant lui. l1 ne se precipite pas vers la zone neutre : d'abord le controle des joueurs et un chemin degage — l2 assure pendant ce temps. r2 peut utiliser sa position devant les bancs pour communiquer avec les equipes. zone neutre r1 pres du haut du cercle ; r2 en diagonale de r1, du meme cote de l'engagement, proche de la ligne bleue. l1 au point ; l2 sur le point d'engagement oppose. responsabilites : r1 les joueurs dans le dos de l1, r2 ceux devant lui ; l2 les ailiers devant l1 et la ligne bleue pour un hors-jeu. les deux arbitres sont prets a partir dans la zone correspondant au sens du jeu ; l2 suit le jeu et couvre la ligne rouge pour l'icing, puis la ligne bleue eloignee. principe constant : les positions se choisissent pour maximiser les angles vers la zone de responsabilite de chacun, jamais pour se ranger symetriquement.",
  },
  {
    n: 22,
    group: 's4',
    title: "R1 — entrée en zone de fin",
    html: "<p class=\"src\">R1 garde le jeu <b>devant lui</b> et patine activement en <b>arrière</b> pour tenir la distance et l'angle. R2 ajuste sa position selon le choix de R1 et ne dépasse pas le dernier attaquant quand le jeu monte.</p> <figure class=\"fig\"><img src=\"@/systems/4-entree-zone.png\" alt=\"R1 vise le coin pendant que R2 remonte pour garder sa ligne de vue\" loading=\"lazy\" decoding=\"async\"><figcaption>Manuel 4 officiels, figure 3.21-1</figcaption></figure> <table class=\"t tx\"> <tr><td><b>1. Jeu du côté opposé</b></td><td>R1 descend <b>jusqu'à la ligne de but</b> ; R2 suit à la vitesse utile pour garder sa ligne de vue.</td></tr> <tr><td><b>2. Jeu du même côté</b>, entre le filet et la bande</td> <td>R1 vise <b>le coin</b> plutôt que de se faire coincer contre la bande derrière le but ; dès que le chemin est libre, il travaille <b>vers le filet</b>.</td></tr> <tr><td><b>3. Jeu qui pousse R1 vers le filet</b></td> <td>R1 <b>change de côté en passant derrière le but</b> pour garder le jeu devant lui, puis reprend la position du cas 1 de l'autre côté. R2 change également de côté en remontant.</td></tr> </table> <p class=\"warn\">R1 ne descend <b>jamais plus bas que la ligne de but</b> : coincé entre le but, le gardien et les joueurs, il devient <i>disconnected</i>. Mieux vaut rester plus haut le long de la bande et revenir vers le filet en patinage actif.</p> <p>Sur un puck jeté en fond de zone, c'est à <b>R1</b> de contrôler que le gardien ne joue pas le puck <b>hors de la zone autorisée</b> ; l'équipe couvre le reste de la glace pendant ce temps.</p>",
    search: "r1 — entree en zone de fin r1 garde le jeu devant lui et patine activement en arriere pour tenir la distance et l'angle. r2 ajuste sa position selon le choix de r1 et ne depasse pas le dernier attaquant quand le jeu monte. manuel 4 officiels, figure 3.21-1 1. jeu du cote oppose r1 descend jusqu'a la ligne de but ; r2 suit a la vitesse utile pour garder sa ligne de vue. 2. jeu du meme cote , entre le filet et la bande r1 vise le coin plutot que de se faire coincer contre la bande derriere le but ; des que le chemin est libre, il travaille vers le filet . 3. jeu qui pousse r1 vers le filet r1 change de cote en passant derriere le but pour garder le jeu devant lui, puis reprend la position du cas 1 de l'autre cote. r2 change egalement de cote en remontant. r1 ne descend jamais plus bas que la ligne de but : coince entre le but, le gardien et les joueurs, il devient disconnected . mieux vaut rester plus haut le long de la bande et revenir vers le filet en patinage actif. sur un puck jete en fond de zone, c'est a r1 de controler que le gardien ne joue pas le puck hors de la zone autorisee ; l'equipe couvre le reste de la glace pendant ce temps.",
  },
  {
    n: 23,
    group: 's4',
    title: "Les 4 zones de la zone de fin",
    html: "<figure class=\"fig\"><img src=\"@/systems/4-zones.png\" alt=\"La zone de fin decoupee en quatre zones, avec la legende R1 / R2\" loading=\"lazy\" decoding=\"async\"><figcaption>Manuel 4 officiels, figure 3.31</figcaption></figure> <table class=\"t tx\"> <tr><td><b>Zone 1</b> — R1</td><td>l'aire la plus proche du filet, y compris juste au-dessus de la zone de but</td></tr> <tr><td><b>Zone 2</b> — R1</td><td>de la bande de fond derrière le but jusqu'aux abords du point d'engagement et vers la bande</td></tr> <tr><td><b>Zone 3</b> — R2</td><td>de la bande basse, depuis le bout du cercle vers le filet, jusqu'au point d'engagement et à la bande — quand R2 a la vue directe depuis la zone neutre ; R1 aide si possible</td></tr> <tr><td><b>Zone 4</b> — R2</td><td>la bande proche de la ligne bleue</td></tr> </table> <h2>Zones de risque</h2> <figure class=\"fig\"><img src=\"@/systems/4-risques.png\" alt=\"Les trois zones de risque autour du filet quand le jeu est profond en zone 1\" loading=\"lazy\" decoding=\"async\"><figcaption>Manuel 4 officiels, figure 3.32</figcaption></figure> <ul> <li><b>Le « côté endormi »</b> (<i>sleepy side</i>) : quand le jeu est profond en Zone 1, R1 est absorbé par l'action ; R2 et les juges de lignes surveillent le côté où le puck n'est pas mais où il reste des joueurs.</li> <li>Jeu <b>dans ou près de la zone de but</b> : R1 est focalisé sur le filet, le risque monte vers les <i>hash marks</i> — à R2 et aux juges de lignes de couvrir.</li> <li>Même logique en <b>Zone 2 et 3</b> : le côté endormi se surveille pendant que R1 est occupé en Zone 1.</li> <li>Le passage de relais est explicite : <b>R1 rend la responsabilité à R2</b> quand le jeu quitte la Zone 2 pour la Zone 4. R2 peut se rapprocher du centre de la glace pour l'angle.</li> </ul> <p class=\"warn\">Dans tous les cas : les arbitres et les juges de lignes ne doivent <b>jamais</b> regarder le puck ou la même zone <b>en même temps</b>.</p> <p class=\"src\">Figures 3.31 et 3.32 du manuel — les zones sont un découpage de travail, pas un tracé sur la glace.</p>",
    search: "les 4 zones de la zone de fin manuel 4 officiels, figure 3.31 zone 1 — r1 l'aire la plus proche du filet, y compris juste au-dessus de la zone de but zone 2 — r1 de la bande de fond derriere le but jusqu'aux abords du point d'engagement et vers la bande zone 3 — r2 de la bande basse, depuis le bout du cercle vers le filet, jusqu'au point d'engagement et a la bande — quand r2 a la vue directe depuis la zone neutre ; r1 aide si possible zone 4 — r2 la bande proche de la ligne bleue zones de risque manuel 4 officiels, figure 3.32 le « cote endormi » ( sleepy side ) : quand le jeu est profond en zone 1, r1 est absorbe par l'action ; r2 et les juges de lignes surveillent le cote ou le puck n'est pas mais ou il reste des joueurs. jeu dans ou pres de la zone de but : r1 est focalise sur le filet, le risque monte vers les hash marks — a r2 et aux juges de lignes de couvrir. meme logique en zone 2 et 3 : le cote endormi se surveille pendant que r1 est occupe en zone 1. le passage de relais est explicite : r1 rend la responsabilite a r2 quand le jeu quitte la zone 2 pour la zone 4. r2 peut se rapprocher du centre de la glace pour l'angle. dans tous les cas : les arbitres et les juges de lignes ne doivent jamais regarder le puck ou la meme zone en meme temps . figures 3.31 et 3.32 du manuel — les zones sont un decoupage de travail, pas un trace sur la glace.",
  },
  {
    n: 24,
    group: 's4',
    title: "Zone neutre & transition",
    html: "<h2>R2 en zone neutre</h2> <ul> <li>Point de départ : autour du <b>point d'engagement</b> de la zone neutre. Déplacements <b>latéraux</b> quand le jeu est profond en zone, <b>verticaux</b> quand il ressort.</li> <li>Une position « active » peut aussi être <b>immobile</b> : ce qui compte est l'angle, pas le mouvement. Mais garder de la vitesse disponible aide à s'écarter du jeu.</li> <li>Quand le jeu est en zone, <b>la philosophie et les zones de responsabilité sont les mêmes</b> qu'en zone de fin.</li> <li>Si R1 change de côté en zone, R2 change aussi pour rester en <b>diagonale</b>. R2 et L1 peuvent alors se retrouver du même côté : ils communiquent pour ne pas se gêner — L1 ne s'écarte pas trop de la bande, R2 ne masque pas la ligne bleue.</li> </ul> <h2>Sortie de zone (Zone 1 de la zone neutre)</h2> <ul> <li>Celui qui passe de R2 à R1 prend la responsabilité du jeu <b>dès que le jeu atteint la Zone 4</b> de la zone de fin, et remonte en <b>patinage arrière actif</b>, jeu devant lui.</li> <li>L'autre garde le contrôle de ce qui reste en zone de fin, puis remonte dès qu'il n'y a plus de joueur à surveiller. Il redevient responsable de la <b>zone neutre</b> (charges en retard, changements de joueurs) quand le jeu la quitte.</li> </ul> <h2>Trois risques en zone neutre</h2> <ul> <li><b>Risque 1</b> — jeu en <b>diagonale</b> à travers la zone : c'est là que se produisent les charges dangereuses, notamment à la tête. Tous les officiels doivent apporter un angle.</li> <li><b>Risques 2 et 3</b> — le long des <b>bandes</b> : charges en retard et charges dangereuses. R2 et L2 ne doivent pas être focalisés sur le puck et gardent ces zones dans le regard jusqu'à ce que le jeu les ait quittées.</li> <li>Les <b>changements de joueurs</b> appartiennent à ces zones : les deux juges de lignes en sont responsables ensemble, avec l'appui de R2 quand c'est possible.</li> </ul>",
    search: "zone neutre & transition r2 en zone neutre point de depart : autour du point d'engagement de la zone neutre. deplacements lateraux quand le jeu est profond en zone, verticaux quand il ressort. une position « active » peut aussi etre immobile : ce qui compte est l'angle, pas le mouvement. mais garder de la vitesse disponible aide a s'ecarter du jeu. quand le jeu est en zone, la philosophie et les zones de responsabilite sont les memes qu'en zone de fin. si r1 change de cote en zone, r2 change aussi pour rester en diagonale . r2 et l1 peuvent alors se retrouver du meme cote : ils communiquent pour ne pas se gener — l1 ne s'ecarte pas trop de la bande, r2 ne masque pas la ligne bleue. sortie de zone (zone 1 de la zone neutre) celui qui passe de r2 a r1 prend la responsabilite du jeu des que le jeu atteint la zone 4 de la zone de fin, et remonte en patinage arriere actif , jeu devant lui. l'autre garde le controle de ce qui reste en zone de fin, puis remonte des qu'il n'y a plus de joueur a surveiller. il redevient responsable de la zone neutre (charges en retard, changements de joueurs) quand le jeu la quitte. trois risques en zone neutre risque 1 — jeu en diagonale a travers la zone : c'est la que se produisent les charges dangereuses, notamment a la tete. tous les officiels doivent apporter un angle. risques 2 et 3 — le long des bandes : charges en retard et charges dangereuses. r2 et l2 ne doivent pas etre focalises sur le puck et gardent ces zones dans le regard jusqu'a ce que le jeu les ait quittees. les changements de joueurs appartiennent a ces zones : les deux juges de lignes en sont responsables ensemble, avec l'appui de r2 quand c'est possible.",
  },
  {
    n: 25,
    group: 's4',
    title: "Icing & changement de lignes (4)",
    html: "<h2>Icing</h2> <ul> <li><b>R1</b> garde le jeu devant lui en patinant en <b>arrière</b> ; s'il ne peut pas, il passe en patinage avant sans perdre la course du regard — des fautes peuvent survenir pendant la course au puck.</li> <li><b>L1</b>, juge de lignes avant, est <b>en charge de l'icing</b> : communication claire avec les joueurs et les collègues pour éviter les situations dangereuses ; patinage actif. Dès l'icing sifflé ou annulé, sa priorité est le <b>contrôle des joueurs</b>.</li> <li><b>L2</b> suit le jeu au-delà de la ligne rouge, puis soutient R2 sur le contrôle des joueurs en zone neutre.</li> <li><b>R2</b> conduit le <b>changement de lignes</b> et vérifie le nombre de joueurs.</li> <li><b>R1 et R2 changent d'extrémité</b> immédiatement après l'icing et rejoignent leur nouvelle position en patinage actif avant l'engagement.</li> <li>L1 apporte le puck à L2, qui demande à l'équipe attaquante <b>de quel côté</b> aura lieu l'engagement, pointe le point choisi et procède. <b>L1 devient L2 et L2 devient L1</b> ; l'ancien L1 passe <b>derrière le but</b> pour rejoindre la ligne bleue.</li> </ul> <figure class=\"fig\"><img src=\"@/systems/4-icing-l1-l2.png\" alt=\"Apres l'icing : L1 remet le puck et devient L2, les arbitres ont change d'extremite\" loading=\"lazy\" decoding=\"async\"><figcaption>Manuel 4 officiels, figure 3.72</figcaption></figure> <h2>Changement de lignes à l'arrêt</h2> <ul> <li><b>Un seul arbitre</b> conduit la procédure : par défaut <b>R2</b>.</li> <li>Si l'engagement redescend la glace (passe hors-jeu, crosse haute), les deux arbitres décident entre eux qui sera R2. En cas de doute : c'est <b>celui qui sera R2 après l'engagement</b>.</li> <li>Position : sur la <b>ligne rouge centrale</b>, aligné verticalement avec les points d'engagement de la zone neutre — la meilleure position pour communiquer avec les bancs.</li> <li>R2 vérifie aussi que les <b>maillots</b> des joueurs qui entrent sont <b>hors du pantalon</b>. R1 garde la vue d'ensemble en se déplaçant vers le lieu de l'engagement.</li> </ul>",
    search: "icing & changement de lignes (4) icing r1 garde le jeu devant lui en patinant en arriere ; s'il ne peut pas, il passe en patinage avant sans perdre la course du regard — des fautes peuvent survenir pendant la course au puck. l1 , juge de lignes avant, est en charge de l'icing : communication claire avec les joueurs et les collegues pour eviter les situations dangereuses ; patinage actif. des l'icing siffle ou annule, sa priorite est le controle des joueurs . l2 suit le jeu au-dela de la ligne rouge, puis soutient r2 sur le controle des joueurs en zone neutre. r2 conduit le changement de lignes et verifie le nombre de joueurs. r1 et r2 changent d'extremite immediatement apres l'icing et rejoignent leur nouvelle position en patinage actif avant l'engagement. l1 apporte le puck a l2, qui demande a l'equipe attaquante de quel cote aura lieu l'engagement, pointe le point choisi et procede. l1 devient l2 et l2 devient l1 ; l'ancien l1 passe derriere le but pour rejoindre la ligne bleue. manuel 4 officiels, figure 3.72 changement de lignes a l'arret un seul arbitre conduit la procedure : par defaut r2 . si l'engagement redescend la glace (passe hors-jeu, crosse haute), les deux arbitres decident entre eux qui sera r2. en cas de doute : c'est celui qui sera r2 apres l'engagement . position : sur la ligne rouge centrale , aligne verticalement avec les points d'engagement de la zone neutre — la meilleure position pour communiquer avec les bancs. r2 verifie aussi que les maillots des joueurs qui entrent sont hors du pantalon . r1 garde la vue d'ensemble en se deplacant vers le lieu de l'engagement.",
  },
  {
    n: 26,
    group: 's4',
    title: "Pénalités — qui appelle, qui rapporte",
    html: "<ul> <li>Les <b>deux arbitres</b> peuvent siffler une pénalité <b>où qu'elle se produise</b> : le critère est la <b>meilleure ligne de vue</b>, pas la zone.</li> <li>Les deux peuvent avoir un bras levé en même temps, pour la même faute ou pour deux fautes différentes. Ils <b>communiquent</b> immédiatement sur ce qui est annoncé.</li> <li>Deux pénalités différées contre la <b>même équipe</b> : R1 arrête le jeu et fait sa procédure ; R2 enchaîne aussitôt la sienne pour confirmer qu'il ne s'agit pas de la même faute.</li> </ul> <h2>Rapport à la table</h2> <table class=\"t tx\"> <tr><td><b>Cas général</b></td><td>celui qui a arrêté le jeu rapporte</td></tr> <tr><td><b>Même faute, zone neutre</b></td><td>celui qui est le plus <b>proche du banc des marqueurs</b></td></tr> <tr><td><b>Jeu en zone de fin</b></td><td>toujours <b>R1</b></td></tr> <tr><td><b>Fautes différentes</b></td><td>brève discussion, un rapporte, l'autre lance le changement de lignes</td></tr> </table> <p>Si un arbitre annonce <b>plusieurs</b> pénalités, montrer clairement <b>chaque signal</b> à tous les joueurs.</p> <p class=\"warn\"><b>Wash-out : à utiliser avec parcimonie.</b> Un wash-out de R1 pendant que R2 lève le bras pour une pénalité envoie un mauvais signal aux équipes et abîme la crédibilité des deux. R1, plus proche, n'a pas forcément le meilleur angle. Même règle pour tout signal officieux : pas de hochement de tête, pas de doigt. <b>Ne rien siffler</b> est le seul « signal » nécessaire quand on n'a rien vu.</p> <p class=\"src\">Si R2 siffle depuis la zone neutre : après le rapport, il <b>devient R1</b> et prend position en zone de fin ; l'autre conduit le changement de lignes.</p>",
    search: "penalites — qui appelle, qui rapporte les deux arbitres peuvent siffler une penalite ou qu'elle se produise : le critere est la meilleure ligne de vue , pas la zone. les deux peuvent avoir un bras leve en meme temps, pour la meme faute ou pour deux fautes differentes. ils communiquent immediatement sur ce qui est annonce. deux penalites differees contre la meme equipe : r1 arrete le jeu et fait sa procedure ; r2 enchaine aussitot la sienne pour confirmer qu'il ne s'agit pas de la meme faute. rapport a la table cas general celui qui a arrete le jeu rapporte meme faute, zone neutre celui qui est le plus proche du banc des marqueurs jeu en zone de fin toujours r1 fautes differentes breve discussion, un rapporte, l'autre lance le changement de lignes si un arbitre annonce plusieurs penalites, montrer clairement chaque signal a tous les joueurs. wash-out : a utiliser avec parcimonie. un wash-out de r1 pendant que r2 leve le bras pour une penalite envoie un mauvais signal aux equipes et abime la credibilite des deux. r1, plus proche, n'a pas forcement le meilleur angle. meme regle pour tout signal officieux : pas de hochement de tete, pas de doigt. ne rien siffler est le seul « signal » necessaire quand on n'a rien vu. si r2 siffle depuis la zone neutre : apres le rapport, il devient r1 et prend position en zone de fin ; l'autre conduit le changement de lignes.",
  },
  {
    n: 27,
    group: 's4',
    title: "Tir de pénalité (4 officiels)",
    html: "<p class=\"src\">L'arbitre qui accorde le tir montre d'abord le <b>signal de la faute</b> (ex. coup de crosse), puis celui du tir de pénalité. Celui qui a arrêté le jeu devient <b>R1</b>. En séance de tirs au but, les deux arbitres décident avant le premier tir qui commence comme R1, puis <b>alternent</b> à chaque tir.</p> <figure class=\"fig\"><img src=\"@/systems/4-tir-penalite.png\" alt=\"Placement des quatre officiels pour un tir de penalite\" loading=\"lazy\" decoding=\"async\"><figcaption>Manuel 4 officiels, figure 3.60</figcaption></figure> <table class=\"t tx\"> <tr><td><b>R1</b></td><td>d'un côté du but, vers le <b>point d'engagement</b> ; surveille le <b>tireur</b> ; siffle le départ après avoir vérifié que tout est en place et que L1 a quitté le centre</td></tr> <tr><td><b>R2</b></td><td>de l'autre côté, <b>le long de la ligne de but</b> ; surveille le <b>gardien</b> et <b>signale le but ou le wash-out</b></td></tr> <tr><td><b>L1</b></td><td>pose le puck au centre, puis recule vers le point d'engagement de la zone neutre côté bancs et <b>suit le tireur à 4-5 m</b> : contrôle que le puck n'est pas joué vers l'arrière</td></tr> <tr><td><b>L2</b></td><td>au <b>banc des marqueurs</b>, face aux bancs des joueurs : surveille les bancs pendant le tir</td></tr> </table> <ul> <li>Si R2 est masqué ou mal placé, <b>R1 peut signaler</b> le but ou le wash-out.</li> <li>Avis divergents entre R1 et R2 : discussion <b>immédiate</b>, décision commune, puis communication aux équipes. Les juges de lignes peuvent être associés s'ils ont vu quelque chose de déterminant.</li> <li>Après le tir : <b>L1 contrôle les joueurs</b>, <b>L2 récupère le puck</b>.</li> </ul>",
    search: "tir de penalite (4 officiels) l'arbitre qui accorde le tir montre d'abord le signal de la faute (ex. coup de crosse), puis celui du tir de penalite. celui qui a arrete le jeu devient r1 . en seance de tirs au but, les deux arbitres decident avant le premier tir qui commence comme r1, puis alternent a chaque tir. manuel 4 officiels, figure 3.60 r1 d'un cote du but, vers le point d'engagement ; surveille le tireur ; siffle le depart apres avoir verifie que tout est en place et que l1 a quitte le centre r2 de l'autre cote, le long de la ligne de but ; surveille le gardien et signale le but ou le wash-out l1 pose le puck au centre, puis recule vers le point d'engagement de la zone neutre cote bancs et suit le tireur a 4-5 m : controle que le puck n'est pas joue vers l'arriere l2 au banc des marqueurs , face aux bancs des joueurs : surveille les bancs pendant le tir si r2 est masque ou mal place, r1 peut signaler le but ou le wash-out. avis divergents entre r1 et r2 : discussion immediate , decision commune, puis communication aux equipes. les juges de lignes peuvent etre associes s'ils ont vu quelque chose de determinant. apres le tir : l1 controle les joueurs , l2 recupere le puck .",
  },
  {
    n: 28,
    group: 's4',
    title: "Vidéo, challenge, majeures",
    html: "<ul> <li>L'arbitre qui <b>demande</b> la révision la <b>dirige</b> : il se rend à la table, contacte le <b>VRC</b> et mène la conversation.</li> <li><b>Avant</b> le contact avec le VRC : <b>débriefing court de toute l'équipe</b> d'arbitrage sur ce qui va être revu et sur la décision qui suivra. Avec des casques de communication, inutile de se retrouver dans le cercle, mais le débriefing a lieu quand même.</li> <li>Pas d'écran à la table : l'autre arbitre <b>reste sur la glace</b> avec les juges de lignes et surveille les bancs — sans commenter la révision ni annoncer la décision à venir. Tablette ou écran disponible : les deux arbitres regardent.</li> <li>Après la révision, la discussion se fait <b>uniquement avec le capitaine</b> de chaque équipe.</li> <li>Si la vidéo n'est <b>pas concluante</b>, la <b>décision sur la glace</b> de l'arbitre prévaut.</li> <li>Celui qui a mené l'échange avec le VRC <b>annonce la décision</b> et devient <b>R1</b> pour la suite.</li> <li>Pendant la révision, les juges de lignes assurent le <b>contrôle des joueurs</b>, sur la glace et aux bancs ; au besoin, tous les joueurs peuvent être renvoyés aux bancs, gardiens exceptés.</li> </ul> <h2>Cas particuliers</h2> <ul> <li><b>Coach's Challenge</b> : même procédure. Pour un <b>hors-jeu</b>, c'est le <b>juge de lignes</b> qui conduit la révision.</li> <li><b>Majeure ou pénalité de match</b> : révision par les arbitres, sauf disposition contraire annoncée avant l'événement. Le <b>VRC ne donne aucune information</b>. Le joueur pénalisé doit être <b>placé au banc des pénalités avant</b> la révision.</li> <li><b>Double mineure pour crosse haute</b> : la révision est possible, jamais obligatoire.</li> </ul> <p class=\"warn\">En <b>SEAF</b>, ni Video Review ni Coach's Challenge ne sont appliqués (fiches de poche 14 et 47) : cette fiche vaut pour les compétitions où la vidéo est en place.</p>",
    search: "video, challenge, majeures l'arbitre qui demande la revision la dirige : il se rend a la table, contacte le vrc et mene la conversation. avant le contact avec le vrc : debriefing court de toute l'equipe d'arbitrage sur ce qui va etre revu et sur la decision qui suivra. avec des casques de communication, inutile de se retrouver dans le cercle, mais le debriefing a lieu quand meme. pas d'ecran a la table : l'autre arbitre reste sur la glace avec les juges de lignes et surveille les bancs — sans commenter la revision ni annoncer la decision a venir. tablette ou ecran disponible : les deux arbitres regardent. apres la revision, la discussion se fait uniquement avec le capitaine de chaque equipe. si la video n'est pas concluante , la decision sur la glace de l'arbitre prevaut. celui qui a mene l'echange avec le vrc annonce la decision et devient r1 pour la suite. pendant la revision, les juges de lignes assurent le controle des joueurs , sur la glace et aux bancs ; au besoin, tous les joueurs peuvent etre renvoyes aux bancs, gardiens exceptes. cas particuliers coach's challenge : meme procedure. pour un hors-jeu , c'est le juge de lignes qui conduit la revision. majeure ou penalite de match : revision par les arbitres, sauf disposition contraire annoncee avant l'evenement. le vrc ne donne aucune information . le joueur penalise doit etre place au banc des penalites avant la revision. double mineure pour crosse haute : la revision est possible, jamais obligatoire. en seaf , ni video review ni coach's challenge ne sont appliques (fiches de poche 14 et 47) : cette fiche vaut pour les competitions ou la video est en place.",
  },
  {
    n: 29,
    group: 's4',
    title: "Secours : 2 arbitres + 1 juge de lignes",
    html: "<p class=\"src\">Utilisé <b>uniquement</b> quand un juge de lignes du système à 4 est blessé ou ne peut plus assurer. Si c'est un <b>arbitre</b> qui sort, l'équipe repasse au <b>système à 3</b>.</p> <h2>Engagements</h2> <ul> <li><b>Début de match et de tiers</b> : « L » engage face au chronométreur ; R1 et R2 sur les lignes bleues, en <b>diagonale</b>, R1 devant le banc de l'équipe locale.</li> <li><b>Après un but</b> : R2 rapporte le but, R1 surveille les joueurs puis conduit le changement de lignes ; l'arbitre côté bancs se place sur la ligne bleue la plus proche du banc de l'équipe qui a marqué. « L » engage au centre, face aux bancs.</li> <li><b>Zone de fin</b> : R1 entre la ligne de but et le cercle, en face de l'engagement ; R2 conduit le changement de lignes puis couvre la ligne bleue et les joueurs <b>dans le dos de L</b>.</li> </ul> <h2>Lignes</h2> <ul> <li>Les arbitres couvrent les lignes bleues à tour de rôle : celui qui remonte prend la ligne, « L » passe à la ligne rouge et lui laisse la responsabilité.</li> <li><b>Hors-jeu</b> : appelé par « L », qui engage ensuite ; un arbitre récupère le puck. Si c'est un arbitre qui siffle le hors-jeu, il va au point et « L » ramasse le puck et engage.</li> <li><b>Icing</b> : géré par les deux officiels de devant. R1 signale en levant le bras sans sifflet à <b>66°</b> vers la zone concernée et patine bras levé — pour ne pas confondre avec une pénalité différée. « L » file à la ligne de but, vérifie avec R1 que l'icing tient, puis siffle ; R1 baisse le bras et <b>croise les bras</b> sur la poitrine.</li> <li><b>Moins de 10 secondes en zone</b> : « L » rejoint la ligne de but pour aider R1 sur la validation d'un but ; R2 reste à la ligne bleue.</li> </ul> <h2>Tir de pénalité</h2> <p>R1 sur la ligne de but signale le but ou le wash-out, R2 l'assiste et récupère le puck, « L » conduit la procédure depuis la ligne rouge.</p>",
    search: "secours : 2 arbitres + 1 juge de lignes utilise uniquement quand un juge de lignes du systeme a 4 est blesse ou ne peut plus assurer. si c'est un arbitre qui sort, l'equipe repasse au systeme a 3 . engagements debut de match et de tiers : « l » engage face au chronometreur ; r1 et r2 sur les lignes bleues, en diagonale , r1 devant le banc de l'equipe locale. apres un but : r2 rapporte le but, r1 surveille les joueurs puis conduit le changement de lignes ; l'arbitre cote bancs se place sur la ligne bleue la plus proche du banc de l'equipe qui a marque. « l » engage au centre, face aux bancs. zone de fin : r1 entre la ligne de but et le cercle, en face de l'engagement ; r2 conduit le changement de lignes puis couvre la ligne bleue et les joueurs dans le dos de l . lignes les arbitres couvrent les lignes bleues a tour de role : celui qui remonte prend la ligne, « l » passe a la ligne rouge et lui laisse la responsabilite. hors-jeu : appele par « l », qui engage ensuite ; un arbitre recupere le puck. si c'est un arbitre qui siffle le hors-jeu, il va au point et « l » ramasse le puck et engage. icing : gere par les deux officiels de devant. r1 signale en levant le bras sans sifflet a 66° vers la zone concernee et patine bras leve — pour ne pas confondre avec une penalite differee. « l » file a la ligne de but, verifie avec r1 que l'icing tient, puis siffle ; r1 baisse le bras et croise les bras sur la poitrine. moins de 10 secondes en zone : « l » rejoint la ligne de but pour aider r1 sur la validation d'un but ; r2 reste a la ligne bleue. tir de penalite r1 sur la ligne de but signale le but ou le wash-out, r2 l'assiste et recupere le puck, « l » conduit la procedure depuis la ligne rouge.",
  },
]
